### ISSUE TITLE
The results need more work

### ISSUE THREAD

**Issue by local-minimum** [JammerCore/JammerCore#1008]
* Current list only promotes games, not person/team that made them.
* It's also really hard to compare between different categories or get any type of comparison/overview.
* There's no flare for top 3 games either.

My first idea is to use the header that is used to display event on the user's game page to display rank and at least partial name.

Then my second idea is to have a hover effect or have an extra footer with voting category icon + rank for all categories.

I also think results could load 24 on non-mobile platforms.

**Comment by povrazor** [comment]
Yeah I had planned to add a context sensitive thing to the bottom right corner. 

* During ratings, an exclamation sign on any game w/o enough ratings
* In general listings, their top place
* In listings for results, the number for that result

**Comment by local-minimum** [comment]
I started working on something here https://github.com/local-minimum/ludumdare/tree/event-results-with-rank but I'm now kind of stuck about how to get the authors and generally testing it.

**Comment by povrazor** [comment]
I had planned to include the icons of authors, but there needs to be a hard cap on that to correctly render.

**Comment by local-minimum** [comment]
Yes, I figured it'd be complex to do good, so I made a new component type as a start.
