### ISSUE TITLE
Coolness Placement

### ISSUE THREAD

**Issue by ajayyy** [JammerCore/JammerCore#1010]
There is no coolness medal on the new site, it does show the amount you rated but still.

**Comment by zwrawr** [comment]
Trophies #783 and #74 are about this.

**Comment by ajayyy** [comment]
Trophies are different though, I mean like on the old site here:
![image](https://cloud.githubusercontent.com/assets/12688112/26376088/4c86e00e-3fd9-11e7-9bf4-a55d5ff81b9a.png)

**Comment by zwrawr** [comment]
So #1011 just be became a thing

**Comment by ajayyy** [comment]
Ok, I just changed this to Coolness Placement, because that's what it really is.

**Comment by ajayyy** [comment]
But, the medals for coolness weren't just top 3

**Comment by ajayyy** [comment]
A bit off topic here, but wow, you've only been in one LD, and you still help out so much. That's amazing!

**Comment by povrazor** [comment]
Yes coolness is indeed missing.

**Comment by local-minimum** [comment]
The coolness score is in the json results `obj.node[0].magic.cool` so I guess it is a matter of ranking everyone that is missing? Or is coolness meant to be everyone over 100 gets 100 and everyone else to the closest integer of their score? If latter it would be a small fix to get it in along the other categories.

**Comment by povrazor** [comment]
> or am i confused?

Exactly.

There are 2 cool concepts. The coolness result is missing, and thanks to Teams it has changed a bit. It's a per-user score, not a per-game score. We don't have a suitable users view, so it was omitted from the results. Coolness scores will be retroactively given though, once implemented.

**Comment by local-minimum** [comment]
Maybe coolness is something, like a flair that you keep till next LD you participate in next to your name. Like if you have 90-100 you get "super cool", and if 75-90 you get "quite hip". whatever the icons would be. 

For results, maybe a separate page on the user that collects stats from all jams they participated in. We could even have garph of their success over time
