### ISSUE TITLE
Theme OPT-OUT?

### ISSUE THREAD

**Issue by chzachau** [JammerCore/JammerCore#1058]
> **Is using the Theme required?**
> Officially no, you are **not** required to use the Theme. We will not disqualify you for disregarding it. To us, the Theme is just a single voting category. Ludum Dare is about encouraging you to make something. The theme is something we do to help everyone with the “blank sheet of paper” problem that artists and creators deal with. It’s easier to make something with **_some_** direction than none.

If a participant wants to ignore the Theme, it would be cool if there was an option to OPT-OUT of that voting category, to avoid discussions about it, wouldn't it?

**Comment by povrazor** [comment]
This paragraph could use something about how despite Theme not being required, users will still judge your game based on how themey it is. This is outside of our control.

We still want everyone to _try_ and use the theme, so I'm reluctant to remove the category.

**Comment by timbeaudet** [comment]
I'd like to keep this one on the table for consideration. LudumDare use to be about creating; trying/doing making _something_. That _thing_ hasn't mattered terribly much. I think if people want to opt-out of theme voting that should be acceptable, and a way to tell other participants that "I didn't follow the theme this time, but I created this _thing_".

**Comment by timbeaudet** [comment]
What was the result, were we going to let opt-out or more strictly force the theme requirement?

**Comment by mikekasprzak** [comment]
It is now optional.
