### ISSUE TITLE
Helping to guide/improve feedback

### ISSUE THREAD

**Issue by karai17** [JammerCore/JammerCore#1156]
I will be the first to admit that I leave mediocre feedback when I comment on a game I've played, but I di try to at least leave *something*. That being said, I think it might be helpful to have a template for feedback that could give people some direction on what to say about the game they are rating, perhaps indicate that they should write a small blurb about each category that the game qualifies for. A simple example would be something like the following:

## How fun was the game?

I liked it! The mechanics were simple and the controls were intuitive.

## What did you think about the graphics?

I felt the graphics suited the game's style. They were simple, but clean.

## What did you think about the sound?

The music was pretty good, but the sound effects felt a bit lacking.

## What did you feel about the mood of the game?

The game had a very distinct sense of humour that had me chuckling to my self. It was very upbeat and silly.

## What did you think of the game over all?

The game was a great entry! I look forward to your next one!

## Did you notice any issues?

I think there was a bug in one of the enemy animations in the third level, it looked like a frame was up-side-down.

---

I don't think many people would take the time to write up that sort of feedback on their own, being prompted to do so would probably increase the quality of feedback significantly. Even making it an option like having a button above the comment box that says "Fill template" might be nice.

**Comment by povrazor** [comment]
Yep! #887

**Comment by local-minimum** [comment]
Possibly a tangential question: Perhaps overall should be listed last, to encourage people to first judge the parts and when that is done reflect over how they've judged the parts and with that perspective judge the whole. If you ask people to first give their overall view and then judge parts, I would guess that you cause them to be more influenced by their compiled judgement in how they judge the parts. (There's probably psychology research on this)

**Comment by karai17** [comment]
that's generally how I judge. I skip overall, judge the parts, then go back
to it. so yeah, I agree, it should probably be last.
