### ISSUE TITLE
Consider: Add a linux 64bit link type & add UI for linux link type.

### ISSUE THREAD

**Issue by sgstair** [JammerCore/JammerCore#1197]
Add Linux 64bit link type and/or add warning UI when you add a Linux link with some suggestions that you export a Universal build version if you are exporting a unity game - This seems like a relatively easy fix that will improve the Linux experience.

See discussion by Jason-kennedy on results thread. https://ldjam.com/events/ludum-dare/39/false-game/results-for-ludum-dare-39

**Comment by povrazor** [comment]
Okay. `Linux 64` should be a child of `Linux`, and the TAG queries should search by id and parent (maybe superparent too).

**Comment by sgstair** [comment]
Proposed solution as implemented (UI suggestions appreciated)
![image](https://user-images.githubusercontent.com/620920/30002651-85511eba-9063-11e7-882a-f2ee584d8d60.png)

Details: I'm looking for a "tag-warning" metadata on tag nodes. If it's present, it's rendered as the warning text below a link. Current progress on this feature is in my fork.

**Comment by povrazor** [comment]
If I recall, the tag list used here is very barebones. I.e. it only contains IDs and Names. So you may not have access to the metadata of the tags here.

**Comment by sgstair** [comment]
Yes, my rough solution (see commit above) does actually fetch the tag's node while you are editing the game, in order to check the metadata for a warning.

**Comment by povrazor** [comment]
Ah, I missed that.

I guess that's not a bad option. It's not like we're loading all tags, just the ones active for the currently displayed game.

**Comment by povrazor** [comment]
My only gripe about this is that this above error only really affects Unity users. That is potentially something we can detect, as I would like to encourage people to tag their game with tools used.

That said, implementing the logic is going to be a bit strange still.

I'm tempted to actually hardcode these sort of tips in to the submission code itself, as eventually 32bit vs 64bit Linux Unity export issues may go away. Not 100% though. I'm open to discussion.

**Comment by sgstair** [comment]
And we're only loading the tag node if you're editing the game, viewers get the same logic as it is currently implemented.

"Issues may go away" => that was my rationale for making it metadata on the tag node - it's something that admins can add/remove as necessary to address current issues.

If we can come up with a better way to detect the unity export, that could work too :)

**Comment by local-minimum** [comment]
If my /fun/link contribution could be added here, we could have more specific feedback/suggestions about the links that the users provide. In any case, I think it would do best if the warning was directly below the problematic link

**Comment by local-minimum** [comment]
I should mention #1025 here I suppose, the link checker I mentioned.

**Comment by povrazor** [comment]
> :information_source: Blah blah blah.
>
> :warning: whoa, blah blah!

The whole submission process needs more information. I want to see more iconography used (i.e. svgicon info, etc).

**Comment by sgstair** [comment]
Agree, I should also mention that I'm planning to update my change to allow markdown formatting of the message. Do we have a mechanism to use site icons in markdown? I've also been thinking about making a reference page to show all the available site icons.

**Comment by povrazor** [comment]
Not yet. Up until recently we couldn't even use components in the markdown, but @Noojuno is a champ and rewrote part of the parser to support that.

**Comment by local-minimum** [comment]
I was thinking about also getting the whole links bit in the UI out of the component-item.js to make changes to it less scary.
