### ISSUE TITLE
Allow love/comment love while not logged in

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#1198]
When you click the love button while not logged in, it should work. Internally, each love entry is stored either by user ID, or IP address. Because this is not an expected behaviour, the implementation on comments omitted this feature.

Also, once this is allowed, the calculate scores functions should ignore anonymous comments as far as the smart filter is concerned.

The purpose of the change is so random people that are not (yet) members can say something is cool. It can technically be abused to make your opinions look to be +1, but so can creating additional accounts. It's a convenience, and abuse cases aren't serious (except the above one that should be fixed before it's allowed).

**Comment by local-minimum** [comment]
Is this something backend, UI or both?

**Comment by povrazor** [comment]
I'm pretty sure it's just UI. I think Jono implemented it, but I hadn't made it clear that it's actually non-standard.

**Comment by mikekasprzak** [comment]
#1996
