### ISSUE TITLE
Articles repository

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#120]
Requires the **Managing Editor** promotion. Grant permission to certain users to publish content to:

```
https://ludumdare.com/articles/
```

i.e.

```
https://ludumdare.com/articles/getting-started-in-unity/
```

Use the `Article` page layout style (no sidebar, no post border, etc).

---

Every user has a personal article repository.

```
https://ludumdare.com/u/mcfunkyparts/articles/getting-started-with-unity/
```

But the `/articles/` URL is preferred, as it makes it looks more official. Articles can be moved from a personal repo to `/articles/` by a **Managing Editor**.

---

**TBD**: Make personal articles available on [jammer.bio](//jammer.bio)

```
https://jammer.bio/mcfunkypants/articles/getting-started-with-unity/
```

---

**TBD**: Consider having articles share the same slug pool as YOUR games.

```
https://ludumdare.com/u/mcfunkypants/getting-started-with-unity/

https://jammer.bio/mcfunkypants/getting-started-with-unity/
```

**Comment by povrazor** [comment]
Have as standard way of marking **Sponsored** content, especially articles.

**Comment by povrazor** [comment]
Because authors of software can publish articles (personal), we may need to mark them. i.e. "this user is an employee of PlayCanvas" or such.

**Comment by povrazor** [comment]
Video articles should be marked differently in the master article's lists.

**Comment by mkalam-alami** [comment]
I like the idea of having a common ```https://ludumdare.com/u/mcfunkyparts/``` root for all contents produced by an user (articles/games). It makes the URLs more informative (e.g. ```/u/jupiterhadley/cool-selection-of-games```), while a common ```/articles``` root makes things less scalable.

OTOH shorter URLs. Plus if you plan to set up redirections for old ```/compo/date/name``` posts, having an username in the URL may complicate that...

**Comment by povrazor** [comment]
Posts and Articles are different. Posts have dates (part of a timeline). Articles are _timeless_... until they're obsoleted and forgotten. ;)

**Comment by mkalam-alami** [comment]
Oh articles are more like Wordpress pages then? My bad.

...So no redirection issue then!

**Comment by povrazor** [comment]
Yes they're basically WordPress pages.
