### ISSUE TITLE
Separate Links, Metrics, and Ratings on game pages, collapse metrics

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#1203]
![postbot](https://user-images.githubusercontent.com/1570313/29794239-184ee7ea-8c15-11e7-8f99-0bc9b5af7562.png)

Game pages are very long.

**Comment by povrazor** [comment]
Metrics actually, they could be a separate tab. Like how you have a tab to select comments. You don't need to be able to see both at once.

Notably, metrics for yourself will be moving to the homepage as part of the participants `/home` page view, so again, seeing your own metrics wont be as important.

Isolating links from the description is more about being able to find it easier when scrolling. You'll see the division line, the dark grays, like seen at the bottom of the image.

**Comment by local-minimum** [comment]
I'll work on this (if I get stuff up and running). Starting by simply removing stuff from the `item.js` and then thinking about redesign. Since they are all vote related, I figured I do folders starting with `vote-` for the different components.

**Comment by povrazor** [comment]
What I would like to see initially is this.

![mettry](https://user-images.githubusercontent.com/1570313/30252263-ece24930-963c-11e7-962c-ac3e090428c8.png)

Right now there's a standalone "tab" for the comments. Metrics can be a 2nd tab.

I'm still not entirely sure what I want to do with ratings (still mulling over some ideas), but definitely moving metrics to separate tab is a good place to get started.

**Comment by local-minimum** [comment]
First I wont restructure anything with respects to how it appears on the page, just make components out of all the part to decrease the complexity of the item-component. Then I'll start testing (and should also make it easier to move stuff around).

**Comment by mikekasprzak** [comment]
#2017
