### ISSUE TITLE
TV: Fetch used by the TV widget ocassionally gives a CORS error

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#121]
Not all the time, but fetch will sometimes give a CORS error in Chrome. Rarely, but I've seen it enough times that it should be looked at.

**Comment by povrazor** [comment]
Interestingly, the error is a 520, i.e. a common error returned by CloudFlare when _they_ screw up.

https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520-Web-server-is-returning-an-unknown-error

Waiting then retrying may be a reasonable way to resolve this. I'll try to remember to copy+paste the error itself.

**Comment by povrazor** [comment]
```
GET http://jammer.tv/v1/live.php/ludum-dare+game-jam+game-dev/

Fetch API cannot load http://jammer.tv/v1/live.php/ludum-dare+game-jam+game-dev/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://jammer.work' is therefore not allowed access. The response had HTTP status code 520. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Uncaught (in promise) TypeError: Failed to fetch(…)
```

**Comment by povrazor** [comment]
Oh! No! It might not be CloudFlare after all.

I got one of these, a much more useful error, ever since I started going direct.

```
Failed to load resource: net::ERR_EMPTY_RESPONSE
```

Now why would the server give an empty response? I should check the logs.

**Comment by povrazor** [comment]
Nothing in the logs. Will have to try an LSWS+PHP upgrade.

**Comment by povrazor** [comment]
Managed to reproduce (unreliably). It apparently timed out (stalled) after 1.17 seconds.

**Comment by povrazor** [comment]
I've noticed CORS errors happen elsewhere on the site when there is a PHP error.
