### ISSUE TITLE
Website (javascript) should appropriately invalidate its cache when it makes changes

### ISSUE THREAD

**Issue by sgstair** [JammerCore/JammerCore#1218]
A few kinds of actions on the site don't currently render properly until you refresh the page:
* Following / unfollowing a user doesn't reflect in your following page
* Adding/removing a user to/from your team doesn't reflect on your published game page. (and has no UI indication of whether it is successful in general)

There are probably some others that don't come to mind at the moment, but I ran into these recently. Basically there seems to be a hole related to links/meta/stars, perhaps those APIs when changing things should cause a js cache invalidate of the affected nodes.

**Comment by sgstair** [comment]
It was also noted that other kinds of profile changes don't update immediately, 
* Setting a profile image doesn't update top right icon
* Setting user description

**Comment by povrazor** [comment]
There's 2 sides to the invalidation:

* Server side (i.e API)
* Client side

I know we've done some of the server side, but I don't believe we've done any of the client side.

**Comment by sgstair** [comment]
Yeah, I think all of the above do correctly invalidate in the server cache now (meta changes and node edit do), but they don't update the object in the client cache. That is a pretty serious gap :)

**Comment by povrazor** [comment]
Well if you know a node is now, you can call.

```
$node->InvalidateNodeCache(id);
```

Next time it's requested, it will actually request from the server. So it looks like I was planning for this, just never actually used it. :wink:

**Comment by sgstair** [comment]
will the top bar rerequest on navigate? If so then maybe this is pretty simple to resolve.

**Comment by povrazor** [comment]
I'm not sure about the top bar, but other cases (editing posts not actually updating) should be trivial to fix. I've dropped the call in to the update/publish/transform calls of node. Just need to generate some data and perform some tests. Then we can fix other cases.

**Comment by povrazor** [comment]
Okay, latest has fixes that should cause invalidations any time a node changes.

Stars (currently how adding friends and team members work) do not work. This is because the actual data for friends is stored in a user's private data. Invalidating the node is not the correct solution to this.

Instead, there needs to be a way to invalidate private data.

**Comment by povrazor** [comment]
Caches invalidate now, but the changes don't cascade triggering re-renders. There's probably a good way to fix this.
