### ISSUE TITLE
Legal: Ludum Dare logo

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#1243]
Today I was asked about the current Ludum Dare logo, and what license it's under.

https://twitter.com/blinry/status/914958766084325376

Right now my focus is getting everyone comfortable with the new website, the new way of things. One area of Ludum Dare the entity I'm sorely lacking is in legal. Both for branding (logo), and other agreements with potential partners. For something as big as we are, I'm reeeeealy behind on this. 

Code wise we're MIT, since I personally disagree with the practices and attitude of the GPL. But as far as branding and operations legalese goes it's still early.

I'm not ready to officiate this license, but it was suggested that the Ludum Dare brand and logo should be licensed under something like this. 

https://creativecommons.org/licenses/by/2.5/ca/

It's certainly my intention to do something like that, but at this time I can't officiate it.

**Comment by zwrawr** [comment]
Any specific reason why your using `Creative Commons by Attribution 2.5 Canada (CC BY 2.5 CA)` rather than `Creative Commons by Attribution 4.0 International (CC BY 4.0)`

**Comment by povrazor** [comment]
Because that's where the Google Search lead me. ;)
