### ISSUE TITLE
Send email on notification

### ISSUE THREAD

**Issue by sgstair** [JammerCore/JammerCore#1284]
The site should email people when there are new notifications that occur since they have last read their notifications. Below is how I am considering implementing it, please provide any suggestions / feedback:

In Magic task (runs every few minutes):
* Discover the first N (maybe 10) users who:
  * Have read notifications since the last notification email
  * Have new notifications
  *  In order of when the last email was sent to them (first user has not had an email in the longest)
* If any exist, produce and send emails to them, and update the email notification ID for the user in DB

On the test site with mailcatcher, it takes about 1 second to send a mail, so at most 10 mails per magic run seems about right, but it's hard to tell.

**Comment by local-minimum** [comment]
I would want two criteria.

* The olsest new notification for the user should be at least a week old. (Dont mail when not needed)
* And it should be at least a week since last mail to the user. (Dont mail too often)

**Comment by sgstair** [comment]
A week seems far too long, but I might agree with a day. Even that seems too long.
The system will not mail again until you visit the site and read notifications though, I think that's possibly enough? 

I know my expectation with a system like this is: I should be notified almost immediately when something happens - Then when I go to the site and interact with it, the system rearms and I again get a notification instantly if something new happens.

**Comment by local-minimum** [comment]
My expectation for not blocking notifications mails is that they are not allowed to be more than one a week, probably less than that to be truly acceptable. But more to the point though, I think our differences show that:

* Mailing should not be implemented if there aren't any user settings
* Settings should allow enable and disable.
* Settings should allow weekly digest, and frequent mailing.

(And as a user I would not find it acceptable if ldjam started mailing me if I can't turn the mailing off)

**Comment by sgstair** [comment]
At minimum I agree an email notifications enable/disable flag should be available. 
Regarding a weekly digest kind of format, would you expect it to always come on a specific day (would you want to control this?), or just, 7 days from the last notification email (if you haven't cleared notifications manually in that time), or immediately if it's been longer than that.

**Comment by sgstair** [comment]
the "stop following this thread" concept also probably needs to be applied before we push email notifications live, so that's part of this work.

**Comment by local-minimum** [comment]
I would probably expect for the weekly digest to come on specific days, but that is less important or rather fridays would be good as ppl tend to play more during weekends. And getting notifications about comments on your game would probably encourage that.

Agree with need for opt out footer link on the mail. Dont know the law exactly and def not intetnationally, but as ppl havent opted in it might be required for it to be legal. (Might also need adress and such to the sending entity)

**Comment by ajayyy** [comment]
I think what's being discussed here is weekly digest vs notification email. I personally would like an email right away for something like ludumdare, because notifications are less frequent. It's really nice to know immediatly that someone commented on your game for example.

**Comment by povrazor** [comment]
I just want to add that this needs to be thoroughly tested and reviewed before it goes live. We need to be extra sure that nothing will cause accidental extra/multiple sends to the same user. E-mail trust is an **extremely** difficult thing to get right, which is why most companies rely on services like MailChimp to handle it for them.

Also I need to move the email server's domain again (final home: `sender_name@jam.vg`), and it will need to build up some credibility again. :sob:

**Comment by sgstair** [comment]
A separate cron is not a bad idea, for many reasons :) Yeah, I understand the complexity of the problem and that it's preferred to fail to send a mail than to double send. I'm pretty confident that the solution I'll come up with will work reliably and easily satisfy your requirements. 
I do plan to log emails sent to a new table, so we can turn it half-on (log to DB, but don't actually send mail) on the live site to look for any trouble there if we want to be super cautious.
And I'll be adding some sanity checking and some opt-out users to the simulator (to identify any unexpected mails). If you have other suggestions for how to test I'd be interested to hear them.

**Comment by local-minimum** [comment]
As a reference, I once hade a bug in a piece of code so that when I tested it, I sent 100000 mails to myself in a matter of seconds. We need this system severely vetted before deployed.

**Comment by povrazor** [comment]
Having a test suite is very good. As a precaution I mainly mean serious peer review, documentation, and discussion. I want to be on the exact same page as you with how everything works, just so I personally feel confident in. I have no doubts that you'll do it right. This is just one of those areas I need 100% confidence that it's going to do exactly what it should do. 'cause if we make a mistake, it cripples our ability to notify users.

**Comment by mikekasprzak** [comment]
Closing this since we now pay per email, to guarantee deliverability.
