### ISSUE TITLE
CloudFlare sometimes discards traffic

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#1385]
It's super annoying, but it looks like the CloudFlare bug still lives, though it has a new interpretation.

![connreset](https://user-images.githubusercontent.com/1570313/33065107-f0f6d18c-ce75-11e7-99ff-5a753d1049bc.jpg)

A user in Moscow, Russia is being incorrectly flagged as bad, and their traffic is being discarded.

https://twitter.com/holyblckcat/status/932773995157565441

No problems accessing the website by any of the workarounds (HTTP, Direct, API).

**Comment by povrazor** [comment]
Not a fix, but a potential helpful addon would be to configure the server's direct URL to use Lets Encrypt. Lets Encrypt isn't a perfect solution (other users have problems with it), but in this case it should be fine. It will be extremely rare that a user has the Lets Encrypt bug AND the CloudFlare bug.

Note that the static URL will continue to CloudFlare, but it's a separate domain, so it may bypass (still waiting for confirmation).
