### ISSUE TITLE
Assumption that newly published games will appear immediately

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#1457]
I've seen a lot of people panic when they don't see their game show up right away.

This is because the metrics lists only update a few hundred games every 2 minutes. With many thousands of games, it takes up to 15 minutes before all games have been updated.

That said, new items are inserted every 2 minutes, but their stats aren't necessarily calculated. This should be checked if the logic updates them too.

Also, it should be made clear (education) that your game wont show up right away.

**Comment by local-minimum** [comment]
I suggest a little notification when pressing publish that upon the 200 response says just This.

**Comment by mikekasprzak** [comment]
Closing this for #2046
