### ISSUE TITLE
Unfinished Games Category

### ISSUE THREAD

**Issue by chzachau** [JammerCore/JammerCore#1476]
I have some questions concerning Unfinished games, because the topic is not included in the rules.

My game is largely _unfinished_, but it is _NOT unplayable_. It's even playable in the browser. There is just placeholder art only, no sound and no win condition. So i marked it as Unfinished, because that's what i'd call it.

I wondered if marking as Unfinished would remove ratings, but to my surprise i recieved 8 ratings after a brief blog post. Compo and Jam games are compared to other Compo and Jam games. What happens if i recieve enough votes in the Unfinished category? Would the average star ratings still be displayed for each category?

I guessed that the "All" games filter would include Compo, Jam _and_ Unfinished.

Is the Unfinished category supposed to be a trash can, like the symbol suggests? Or does Unfinished equal unplayable? If somebody marks his own game as Unfinished, doesn't this mean he wants to show existing parts of the game (and be rated for parts of the creation)? Otherwise he would step away from publishing completely, right?

**Comment by zwrawr** [comment]
My take on it is:
> The intent of the unfinished category is too give you a way to publish your game if you gave up or didn't manage to finish in time.

**Comment by povrazor** [comment]
It's supposed to be the "I made something, but I don't feel it deserves a rating" category. I'm actually really surprised to hear you got ratings, but in hindsight I never actually disabled that. By default it's omitted from the standard filters. You need to explicitly select it. Also we don't generate any charts at the end for unfinished games.

**Comment by pfefferminzz** [comment]
I know this is very low priority, but could you generate the average stars at the end (without placement), if it's not too much of a hassle, please?
