### ISSUE TITLE
Make a galley, for images a user has already uploaded.

### ISSUE THREAD

**Issue by zwrawr** [JammerCore/JammerCore#1477]
> (22:59:02) bitslap: where can i see uploaded files

Kind of like this, where dive/photos is a list of previously uploaded content
![screenshot from 2017-12-05 23-04-53](https://user-images.githubusercontent.com/18352787/33635657-bb87bde4-da10-11e7-981b-6580dd1fa4d5.png)

**Comment by povrazor** [comment]
We have the data too. A table dedicated to remembering everything you've uploaded.
