### ISSUE TITLE
ludumdare.com: Switch legacy to legacy.ludumdare.com

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#149]
All posts need to be edited, correcting all local image URLs to now point to [legacy.ludumdare.com](https://legacy.ludumdare.com).

**Comment by povrazor** [comment]
Pushing this back. Decided to "not break the internet", and keep the wordpress site running on ludumdare.com, for now.

**Comment by mikekasprzak** [comment]
New plan for this: **do** move to `legacy.ludumdare.com`, but set an end date on the legacy website.
