### ISSUE TITLE
If you edit your profile you easily get stuck in editmode

### ISSUE THREAD

**Issue by local-minimum** [JammerCore/JammerCore#1491]
It is too hard to find a way back... And if you click your avatar on the navbar you end up in a limbo state.

**Comment by povrazor** [comment]
Can I get you to post more details while this is fresh? I'm not going to be able to look at this for a few days.

**Comment by sgstair** [comment]
it's a minor mode glitch - If you edit your profile, then click the profile icon, you get your profile but the description is still in edit mode, though you're not at the edit page. Going to any other page and then back to the profile resets it to normal.

**Comment by pfefferminzz** [comment]
I have the same 'issue' with game editing (via /40/name-of-game/edit). when i save and navigate back to "My Game" (/40/name-of-game/) the edit mode is still active from before. Pressing F5 works in this case.

**Comment by local-minimum** [comment]
I agree it is a general concern that it is too easy to get stuck in edit-mode in a confusing way.

**Comment by mikekasprzak** [comment]
I believe this is fixed by the [ :heavy_check_mark: DONE ] button.
