### ISSUE TITLE
Expose the actual number of ranked games in the API

### ISSUE THREAD

**Issue by zwrawr** [JammerCore/JammerCore#1531]
* The threshold to be ranked is not actually 20, expose the actual threshold once the results are announced
* Expose the number of games that were over that threshold when the event finishes

**Comment by Cerno-b** [comment]
This ties in to the request of computing proper percentiles (if we want to base the percentiles off the ranked games and not all submitted games)

https://github.com/ludumdare/ludumdare/issues/990

**Comment by mikekasprzak** [comment]
Exposing the threshold probably wont happen. It's not exactly stored anywhere. It's determined by looking at the data, and seeing how low we can go without causing significant anomalies to the top 100. And besides, we want everyone to still shoot for 20, no matter what we use. The **only** guarantee we make is that if you have 20 ratings, you will get a score.

As for exposing the number of games over the threshold, or specifically, number of games with a score, sure.
