### ISSUE TITLE
CORE: Post Articles

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#156]

**Comment by povrazor** [comment]
In `article-view`, unlike `single-post-view`, minimize comments. 

Comments are allowed, so you can make/give corrections, but de-emphasised for the sake of making article pages look more concise.

**Comment by povrazor** [comment]
Lowering priority.

**Comment by povrazor** [comment]
"Articles" are like WordPress "Pages". They will be formatted slightly different, and may support additional formatting features.
