### ISSUE TITLE
rfe: Make 'Real-World Gathering' a user-postable type of Post

### ISSUE THREAD

**Issue by bremco** [JammerCore/JammerCore#1589]
Current situation: A (non-admin) user can create untyped posts. To read, they can select '[home]' (show all), 'News' (show only news) or 'Feed' (show only normal posts).

Proposed situation: A (non-admin) user can create posts with the type 'normal' or 'Real-World Gathering'. To read, they can select '[home]', 'News', 'Feed' or 'Real-World Gatherings' (which should only show posts of that type, perhaps represented with a globe-icon).

This would (perhaps, partially?) solve the situation where Real-World Problems get in the way of remembering to post a Real-World Gatherings news thread and keeping that up-to-date, and all the hassle that involves.

Perhaps other 'types' of posts could be useful as well.

**Comment by mikekasprzak** [comment]
Yeah the goal is to do something like this. On the TODO list is something called "Communities" (#797). It's a bit broader than just gatherings, but we realize Ludum Dare is so large that many smaller sub-communities exist.
