### ISSUE TITLE
`mail.ru` email is incorrectly flagging LDJAM emails

### ISSUE THREAD

**Issue by JustMegaAlex** [JammerCore/JammerCore#1599]
Just like in title. No e-mail. No account. No jam. Ohhh.... help.
My e-mail (actually not mine) blablabla@mail.ru.

**Comment by JustMegaAlex** [comment]
Thank you for reply! That's right, I entered my e-mail but didn't recieved an activation e-mail after that.
Not quite understand what you mean <you might need to whitelist hello@jammer.vg.> . Could you add some explanation?...Please?)

**Comment by mikekasprzak** [comment]
If you're not receiving our e-mails, that likely means your e-mail provider has some sort of spam filtering, and we're being incorrectly flagged as spam. I would double check your spam folder.

Most hosts let our e-mails through no problem, but some hosts like Hotmail need you to personally white-list the address. To do that with Hotmail, you add the address to your address book. I'm not sure exactly the procedure for `mail.ru`.


Also for future reference for myself (hey me), look here:

https://help.mail.ru/enmail-help/rules/technical

Don't bother reading that. This is just a note for myself for when I have time to dig a little deeper in to why `@mail.ru` emails might not be delivered.

**Comment by JustMegaAlex** [comment]
Ahhh....right you are! totally forgot to check spam folder. Thanks!)

**Comment by mikekasprzak** [comment]
Did you find the e-mail?
