### ISSUE TITLE
Fork/Isolate the JavaScript timezone code

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#1601]
Right now we're using some custom code to figure out the local timezone depending on what the browser tells us.

![ld41count](https://user-images.githubusercontent.com/1570313/38832187-c6c699d2-418f-11e8-9ba6-4be822fce1ae.png)

It's not perfect, but I want to be able to use the code in other projects, and to separately track and resolve bugs with it.

**Comment by zwrawr** [comment]
We should probably just use an existing solution https://momentjs.com/timezone/.
- The ten-year range is 9.1k gzipped.
- Just the code is 2.6k gzipped
    we have to provide some timezone data, but if we just server the current year and make it update the filesize would still be small
- It has 3.3m weekly downloads and 4,000 dependants on npm.
    So it should work well
