### ISSUE TITLE
rough age in posts use "in the future"

### ISSUE THREAD

**Issue by Jan5366x** [JammerCore/JammerCore#1611]
Sometimes very new posts show **"in the future"** instead of **"right now"** which sounds very strange.
(german timezone)

this could be simply avoided by changing the getRoughAge(time) method or clamp the input like:
`getRoughAge(Math.max (0, time_diff));`

**related files:**
- time.js
- notification.js
- comments-comment.js
- common-body-by.js
- headliner.js
- ...

best regards

**Comment by local-minimum** [comment]
I think we can just replace "in the future" text with "right now" and pretend that everything is fine. Should be a quick fix that way.

**Comment by Jan5366x** [comment]
Would be ok since the code doc say it should only handle the past. (just remove the related case)

**Comment by mikekasprzak** [comment]
Marking this as a research issue. I primarily just want to know why (and when) this happens.
