### ISSUE TITLE
Concern about game content figures

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#1613]
![gameswa](https://user-images.githubusercontent.com/1570313/39028780-84423d3e-4426-11e8-93a4-f2dd29770dc8.png)

In the image above, you can see a small 4, but only 3 games.

I got a concerned e-mail from someone that didn't want it to be public that they didn't finish a Ludum Dare, and technically this is the case. Their number is 3 right now, but they only have 1 published game.

**Comment by local-minimum** [comment]
I looked at it now and it picks the number directly from `games` on the user node so this is a back-end issue. However, I'm now also a bit concerned that some people will not like removing their unfinished things from the stats and they may feel we are saying it doesn't count if you only attempted.

**Comment by mikekasprzak** [comment]
The figures are also messed up. Several people accidentally (?) publish
their game without realizing they should only do that when they're done, or
they create a game without realizing their other team member did that
already, etc. Overall it's messy.
