### ISSUE TITLE
Connect ldjam.com and ludumdare.com accounts.

### ISSUE THREAD

**Issue by local-minimum** [JammerCore/JammerCore#1616]
This would allow to have a more complete stats about participation on the user profile and possibly show those games in the game-view too.

I'm thinking a new string the the meta of users and an input-field for setting it. This can of course be abused, but maybe it's not that fun abusing. It could be made safer if the backend checked that the account you want to link to is not already linked to. That might cause some e-mails to Mike though if people find it fun to abuse for some reason.

For this issue I would suggest just adding a link in the profile page (both expanded and collapsed (game view)) to profile page on the old site..

**Comment by mikekasprzak** [comment]
Data will be migrated over, and old site will be eventually retired.

**Comment by local-minimum** [comment]
Sure but this would still need doing to connect accounts with different names and emails.
