### ISSUE TITLE
Add Post-Compo/Post-Jam submission support

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#1641]
It's somewhat common that folks take their Ludum Dare games and continue working on them after the event. This is encouraged, because we exist to inspire. Unfortunately the consequences of this is that many users want to share the latest version of their game with their players, but for fairness players should be playing the Jam version, so we tell folks to list the changes, and to link both versions. Unfortunately many people would prefer to play the latest and greatest.

The result is concerned e-mails from folks worried about cheating. We can do better here.

The ideal solution is to add proper "post-compo"/"post-jam" game submission support. This way, the updated version's details, comments, and feedback can go on that page. We can auto-link to the updated page. The goal is to preserve the compo/jam page as a stepping stone towards a bigger game, and to hopefully remove that "feels a bit like cheating" feeling.

**Comment by mikekasprzak** [comment]
Yeah just a meta link, and a new subsubtype (I forget what I called these I
my notes). I considered making them children of the game itself, but the
URLs are already quite long.

We need this for migration too, as we have several notable post-compo
games. Plus I've had a bunch of people contact me about late games, and
wanting to submit games based on old themes.

**Comment by local-minimum** [comment]
So we need to have more than one category in which you can add a game (a `jam` that happens to be active and the `post-jam` category). We also need that you can post several games to the same category. We might need to have some categories limit the number of games you can post.

**Comment by mikekasprzak** [comment]
I believe I had a single name for all post-event games, irregardless of the
event they we're part of. And limitations are already in effect (i.e. you
can only create one item/game per event), they just need to be set.

The only thing missing in the backend is a way to specify multiple
"can-create" types that are currently active for an event. I.e. comma
separated, pipe separated, or something. That and to have the constraint
code properly parse it.

So the majority of the work is frontend.

**Comment by mikekasprzak** [comment]
Closed per #2026
