### ISSUE TITLE
Notifications may not fit the mobile screen

### ISSUE THREAD

**Issue by Yngwarr** [JammerCore/JammerCore#1645]
![Screenshot](https://user-images.githubusercontent.com/1721439/39563185-4c7dd65c-4ed9-11e8-8d1a-e95202a80e99.png)

That's what I'm talking about.

**Comment by local-minimum** [comment]
Yes, this is known. Someone with more CSS skills than me need to look into that.

**Comment by Yngwarr** [comment]
Huh! Actually, I can do it. =)

**Comment by crs38c28** [comment]
It's in [here](https://github.com/ludumdare/ludumdare/blob/master/src/com/view/bar/bar-notifications.less)
```
	& .-items {
		width: 480px;
		max-width: 480px !important;
		right: 0px;
		top: 55px;
		background: @COL_W !important;
```

change width can solve this problem.

![size](https://i.imgur.com/mdjjkDQ.png)

maybe use ```width: calc(100vw - 2em - 48px);``` can fix this?

But it seems like calc() in LESS ( < 3.0) is different...

 => [[more information]](https://stackoverflow.com/questions/11972084/less-aggressive-compilation-with-css3-calc) , [[more information]](https://github.com/less/less.js/issues/974)

**Comment by Josh6680** [comment]
I had a different approach to this where the position becomes "relative" to the top-right corner below the top bar, and 100% wide for screens that are smaller than the max-width.
```diff
--- a/src/com/view/bar/bar-notifications.less
+++ b/src/com/view/bar/bar-notifications.less

        margin: 0px !important;

        & .-items {
-               width: 480px;
+               width: 100%;
                max-width: 480px !important;
                right: 0px;
-               top: 55px;
+               top: 64px;
                background: @COL_W !important;
+               position: fixed;

                & .-item {
                        padding: 0px !important;
```
Here's a GIF of this while resizing the screen using Firefox devtools:
https://user-images.githubusercontent.com/1106285/40889543-6158b3ba-6736-11e8-8070-c43b494d29a1.gif

**Comment by local-minimum** [comment]
I'm fine with either just as long as we get one in.

**Comment by mikekasprzak** [comment]
Opened a new issues (#1684) for the `lesscss` upgrade. There was a bug in `lesscss` that was holding us back, but it might be fixed now.

**Comment by mikekasprzak** [comment]
I'm re-opening the issue (even though it's resolved) for later when _future me_ gets a chance to look at the notes above. We have a long list of mobile screen fitting issues, and I want to understand some of the proposed fixes if they can be used to resolve some of the other related issues.

**Comment by local-minimum** [comment]
changed tags so it is clear that this isn't as important anymore.
