### ISSUE TITLE
Game Link Parser

### ISSUE THREAD

**Issue by Samusoidal** [JammerCore/JammerCore#1656]
The game publishing/updating mechanism should have some sort of parser to make file share services like Dropbox, Google Drive, Mega, etc. instantly downloadable.

Dropbox:
Just add ?dl=1 to the end of your Dropbox link.

Google Drive:
@Josh6680 said: For GDrive links like these:
https://drive.google.com/open?id=some-id-here
https://drive.google.com/file/d/some-id-here/view?usp=sharing
You can turn them into this for instant download:
https://drive.google.com/uc?export=download&id=some-id-here
Note that the file has to be shared correctly on GDrive for this to work (anyone who has the link can view, disable download unchecked).

**Comment by mikekasprzak** [comment]
The problem is if these change, then links to these websites will break.

**Comment by Josh6680** [comment]
That's really a risk with any links to a third party service. If they decide to change their link structure, and don't provide backwards compatibility, the links will break everywhere on the internet regardless of if they were pasted by the author or if they were transformed automatically.

Keeping the original link stored would help mitigate this problem where the transformed link breaks but the original link is fine, then you could re-parse them into a newer format or disable the transformation.

As a potential compromise you could have beside any GDrive/Dropbox links, another smaller link such as "(direct download)", then you'd have both links available in case the direct link no longer works, which would also buy you some time to update the code.

**Comment by local-minimum** [comment]
I did a backend implementation for getting such data way back, think it is somewhere in the repo where unused ideas are
