### ISSUE TITLE
NaN next to rating

### ISSUE THREAD

**Issue by local-minimum** [JammerCore/JammerCore#1717]
![image](https://user-images.githubusercontent.com/8041100/44021950-71ffc8ba-9ee6-11e8-91cb-d5f93078264b.png)

I'm not sure what it's supposed to be, but I'm not a fan. Suggest hiding that part of the component until whatever it is can be calculated.

**Comment by mikekasprzak** [comment]
Where do you see this? It's supposed to be zero (like the result of a division by zero).

![screenshot from 2018-08-13 13-13-03](https://user-images.githubusercontent.com/1570313/44046831-b0cfb8e8-9efa-11e8-9c6a-4a24c96e9362.png)

**Comment by local-minimum** [comment]
It was https://ldjam.com/events/ludum-dare/42/everyone-chess but now it shows zeros, so I suppose there was some strangeness going on.

**Comment by mikekasprzak** [comment]
Ah, it could have been a moment before some "magic" data was available (i.e. populated by the cron job). Will have to take a look at the code that generates those and see if I'm expecting something to exist that may not exist.

**Comment by local-minimum** [comment]
Or I could check the render and just say 0 on NaN

**Comment by ajayyy** [comment]
I've seen NaN before as well, after refreshing it showed the actual ratings I made previously

**Comment by local-minimum** [comment]
Alright that probably means a request times out or there's a unlikely race condition between requests that sometimes goes the wrong way.
