### ISSUE TITLE
Please add LÖVE to the available platforms

### ISSUE THREAD

**Issue by Rami-Sabbagh** [JammerCore/JammerCore#1724]
LÖVE is an awesome games framework for Lua developers, It has the game files in a universal `.love` file (it's a `.zip`)

It would be an option for people who has LÖVE installed to download the `.love` instead of native builds (which will save them like 5/10 mbs)

**Comment by mikekasprzak** [comment]
Added.

**Comment by Rami-Sabbagh** [comment]
Thanks!
