### ISSUE TITLE
Changing avatar image breaks something

### ISSUE THREAD

**Issue by local-minimum** [JammerCore/JammerCore#1735]
As can be seen on https://ldjam.com/events/ludum-dare/42/moving-out the main author's avatar image isn't showing in the comments. 

There's a request for an image https://static.jam.vg/content/ffe/f/z/1958e.png.64x64.fit.png that returns 500:
```json
{"status":500,"message":"PROC ERROR [99]: ","data":{"user":65279,"asset":{"width":320,"height":320,"mime":"image/png","size":218762}}}
```

There's also an error in the console
```
Potentially unhandled rejection [1] ContentCommonBodyLink</e.prototype.render@https://ldjam.com/-/all.min.js?v=4399-7709f93:1:306918
```

**Comment by local-minimum** [comment]
That user-number matches the id of the user `2bam`, who's icon is missing.

**Comment by 2bam** [comment]
I've tried JPG and PNG [attached](https://user-images.githubusercontent.com/8461554/44160758-d63faf00-a091-11e8-8883-d293147a1ec1.png)
320x320 so I guess the image gets converted and it's not the source image the issue. I also have HTTPS Everywhere, Privacy Badger and Ad block plus plugins in Chrome (latest ver 68.0.3440.106 (Official Build) (64-bit)). Maybe some REST step fails?

**Comment by 2bam** [comment]
Tested another image (photo) and worked. The offending image JPG was downloaded from facebook, PNG was saved in MSPaint and **both fail**. It's definitely has to do with the content or dimensions because two different formats fail.

**Comment by mikekasprzak** [comment]
![](https://static.jam.vg/content/ffe/f/z/1958e.png)

This is what it's supposed to look like?

**Comment by 2bam** [comment]
Yes, looks glitched I know, because it was! and then edited. I like that
aesthetic.
