### ISSUE TITLE
24 hour format

### ISSUE THREAD

**Issue by joleeee** [JammerCore/JammerCore#1746]
Not that important but it would be useful. Maybe it would guess based on your location? I found it at bit confusing when it said the jam started 12:00AM, as a guy that is used to the 24 hour format that does not make sense. Here the time 24:00 is impossible, it should be 00:00 but again, this is just nitpicking.

**Comment by local-minimum** [comment]
I'm all for 24h clock. It's the standard after all. I thought we had an issue for this or we just discussed it on one of the other...

**Comment by local-minimum** [comment]
I just want to bump this again as it now is extremely confusing for Europe where many of us don't use am/pm and there's no standard for what 12am or 12pm means (and that is when the event starts for us)
![Screenshot_20190904-194810](https://user-images.githubusercontent.com/8041100/64278645-89a16d00-cf4d-11e9-9a98-9c1d3b4cfe60.jpg)

**Comment by joleeee** [comment]
![bilde](https://user-images.githubusercontent.com/24441708/64325122-dcb80600-cfc7-11e9-821c-fd47037be265.png)
I think it may be fixed? I barely recall writing this issue.

**Comment by local-minimum** [comment]
Not on mobile at least where you don't see the sidebar you still get an am/pm thing at the top

**Comment by local-minimum** [comment]
![Screenshot from 2019-09-05 11-25-23](https://user-images.githubusercontent.com/8041100/64329647-e34a7b80-cfcf-11e9-9b42-bff48158b6e7.png)
This bit is still bad
