### ISSUE TITLE
Making joining event process more informative and intuitive

### ISSUE THREAD

**Issue by local-minimum** [JammerCore/JammerCore#1752]
Clicking the join-button should in the background create the placeholder game-post as it does now, but it should __not__ redirect you to that page since you most of the time won't have business there yet instead it should redirect you to an educational page on the event that explains the parts of the event, what they are for and what is expected of the user in each part.

When the user presses `Publish` on their game they should probably be redirected back to the same page to the heading of how the voting works.

Something along these lines for LD:

# Welcome to Ludum Dare `{number}`!

If this is your first time here. Please take your time reading through these instructions. It can be quite overwhelming the first time and it is very easy to miss important pieces. At least read this first section now and maybe come back later as the event progresses.

Ludum Dare is a game jam were thousands of people around the world make games either as teams or solo. It is a process that is spit into three main parts:

* __Theme selection__ which is optional but really good for hype. Together we come up with ideas, prune them and vote on which will become the theme. It is kind of customary that a large fraction of the participants will find the theme annoying, but that's part of the challenge.
* __Game making__ starts when Mike announces what is the theme for the event. You will have either 48 or 72 hours to make your game. Different rules apply, so check them before you you start.
* __Playing others' games, rating them and giving them good feedback__ is as important and mandatory as the making of games. This is a three weeks period during which we check out what others' made and help them grow and become better developers. _We expect __everyone__ to play and rate at least 20 games._

## I'm in post

A lot of people write a post when they join. Like you just did! They say that they will be partaking and usually list what tools and techniques they plan to use. Maybe they include a screenshot of where they'll be working, the pet that will be helping them... and so on.

If they plan to do the jam and have some own tools they're planning to use, this is a good time to share them since the rules stipulate that pre-made tools need to be publicly available. 

These posts can look a bit boring, but they also serve the purpose of orienting everyone in new tools that could be interesting to try out. Maybe you should try a new game engine?

## Theme selection

There are some general guiding principles about what is a good theme:

* It should not be hurtful or derogatory.
* It should be inspiring for everyone. This is a tricky thing since it means that the theme needs to work for those that want to work in VR, AR, mobile, 3D, 2D, text only, and audio only at the same time. In other words, most themes that restrict or describe mechanics are highly problematic.
* It should also be fun to play 20 games, preferably a lot more than 20. If the theme only have one very narrow interpretation that makes the vast majority of all submissions play very similarly, the voting period becomes quite tedious.
* It should not be too similar to the last couple of Ludum Dare themes. It would be very fine to reprise a theme from say Ludum Dare 9 because that was years ago, but if the current theme is just a rephrasing of what was the theme two events back, then a whole lot of us that keep coming back for more Ludum Dare will feel very disappointed.

With the exception of the first principle, you can choose to disregard the guidelines. If you really want to suggest "Only one button" and then vote for it. Go ahead and do that 😉 .

All these could be summarized as: _A good theme is a theme that is good for almost everyone_.

## Games making
There are two parallel events. The compo and the jam. They run for 48 and 72 hours respectively. The compo has more restrictions. Basically you have to work solo, do _everything_ yourself during the 48 hours and publish the source code. The jam is more relaxed and you have an extra day. You can work as a team or solo. So it is quite common that people start out with the idea of making a compo-entry but realize they need an extra day and submit to the jam. Jam is also the largest of the two events and by no means second to the compo, so don't think of one as better or cooler than the other. Choose the one that suites your interests the best.

In other words: If you plan to make a compo-entry, you kind of have to aim for it from start. But with the jam you can always decide to settle on later.

Check out the rules for the two at: `{link}`.

### Social

Some people stream their development, a lot more post here on ldjam.com about their progress, and some write post-mortem ('what we learnt/went good/bad'), some tweet their progress. You don't have to decide the level of presence you want for yourself, but it is a good idea to at least grab a few screenshots as your progress. Just in case. And you will want some images when you present your game and those screenshots may well become one of them.

Some hang out here on ldjam.com in the main feed. Some hangout on twitter, irc, or discord. They're good places to get help and support and just have more fun. Some just do their game and submit it. All these are fine. Common posts during the development are Day 1 and Day 2 progress. Meal photos are also quite common.

### Lessons

Those of us that have done a bunch of these events have also learnt some general lessons that are probably true for most of us:

* _Limit your scope! No, limit it even more!_ It is hard to stress how short 48/72 hours is so make sure you have a very limited core game/experience that will be a fun and complete whole on its own and then have all the grand visions be modular extensions of that core idea. You might find the time to add one or two of them later.
* _Take breaks_, _take even more breaks_, _eat_ and _SLEEP!_. As short as 48/72h are, they are also very long and it will only cause more time spent hunting bugs or making bad decisions towards the end when everything is stressful if you're not rested and fed. And that is no good.
* _Your game is probably too hard_. This is a really tough one. But you'll be playing and replaying the game, especially the beginning so many times. And you know exactly everything that is happening, why it is happening and when. It is one of the most common mistakes, that the game starts too difficult and ramps up in difficulty way too fast. For the people playing it, they will come out of your game with a much better feeling if you allow them a decent chance to win/complete it. This doesn't need to relate only to reaction times and such skills. It can also be the number of key-actions to remember on the first level, puzzle pieces or rules from start or simply the amount instructions before you get to play.
* _Did you really explain that?_ This is kind of the same as the previous, but also more basic. You know why things happen. If you're not sticking to genre tropes, it becomes increasingly vital to help the player understand how to even interact with your game. What their goal is. What are bad action what are good. Is it as clear as you think it is and clear enough that the player understands anything.
* _Can everyone play this?_ Well you don't have to make a game for everyone, but it really doesn't hurt to consider http://gameaccessibilityguidelines.com/ or you may make the game unplayable to left-handed, color-blind, make people nauseous and so on. It can be quite a large proportion of players you lock out and this will only hurt you during voting because they will probably try and not have as fun.

### On time management

A lot of people strive to have something they can play by the end of Saturday and dedicate Sunday (and Monday) to extend, make prettier, add stuff like menus, high-scores, ending, instructions.

This also means you should probably not spend an eternity making all assets perfect before you go on to the next, but you should still spend enough time that you are fine with not having the time or energy to return and refine them, because most of them you will not manage to improve.

### Submission hour

After the end of the 48h/72h there's a short time to build and publish the game. Check out the rules about what improvements are allowed even afterwards. But also consider not waiting until the very last minute. It is not only stressful for you, the site often becomes severely overloaded and it can be hard to connect. For this reason it is also good to stay off the site close to and during submission hour if you're already done and submitted.

## Playing, rating and commenting

This is really as important as making games. It is critical to understand that this is a community effort. There will be winners in the different voting categories in the end, and those people will be very happy, but there's no prize and there's much more to it than simply scoring well. This is one of the few chances many of us to have to get more than five people play our games and even get a bunch of relevant feedback from people who know something about making games. 

As written above, we expect you to play and vote on at least 20 games. You don't have to, and it's more important that you play fewer games more thoroughly than just spending 30 seconds on a game and giving it semi-random grades. If you have to choose, it's always better to play fewer games and write useful comments. We'll get to that later. Even if you're stressed about reaching 20 games, this strategy will probably help you the most.

The way the game-feeds on the event works they are geared towards promoting those games who's makers have been good towards the general community in having voted on many games and given valuable feedback. The details of how this works changes over time, but it means that when you vote on game you take away some of their hard earned visibility. So don't steal their effort by a quick check of the game, sloppy grading and no feedback!

There's another reason to write good feedback. A lot of people play back all or most of those who commented on their game rather than only relying on the games feeds and so a good comment is a really good way of scoring some extra, and extra good, feedback for yourself.

### Good feedback

Having given a game a serious opportunity, good feedback:

* Is respectful.
* But this doesn't mean it can't be critical.
* In fact, it's good to say where you didn't understand things, how far you got, if there was things you didn't like or even offended you.
* But remember to say something nice too even if it really wasn't your cup of tea.
* Be specific. Bring up some examples of what you liked or didn't. For example "I liked the chirp sound when picking up the coins, it made me laugh every time" is way better than "The audio was great".
* If you stream and/or record yourself playing, insert a link to the clip!
* Suggest what you would focus on as improvements. Many people make post-jam versions some even go on to make full releases of their games and then this is really appreciated. And even if they don't want to update it, those suggestions may become good lessons for next jam.

### Good behavior

As a community we are split on what drives us. Making the game, getting good grades, getting good feedback. So be mindful of this and treat everyone as if they care most for all aspects.

There will always be those that don't manage to get the needed 20 votes to have the right to be ranked in the final score, and so towards the end of the voting it is considered good get as many games over that threshold as possible even if they didn't deserve it themselves.

## Results and Post-Mortem

Ludum Dare isn't really about winning, but to most it is still exiting to see how we did. Was it an improvement compared to last time? There's a whole bunch of games being made, so ranking top 100 in any category is really good, if ranking isn't fore you, then that's absolutely fine too. It is really up to you what you care about, if you care at all. And if you scored lower than you expected, don't take it personally. It does happen to most of us from time to time. Hopefully you got some useful comments or learnt something from the process and if you come back next time, you'll probably score higher!

This is also a time when a lot of people write up a summary of their experience of Ludum Dare and their game. The positive and the negative. Lessons learnt. Lessons never learnt. Check out post-mortems if you're interested or just come up with your own way of summarizing the experience. 

Remember to follow some people that seemed nice or interesting -- people that gave exceptionally good feedback, made interesting games, that sort of thing. Following them will help keeping track of them the next event. It also makes it more fun to see how people who keep returning evolve over time. Maybe you can find a new friend or someone to collaborate with.

Hopefully you will return you for more Ludum Dare! But most importantly, we hope this Ludum Dare was a blast!

**Comment by local-minimum** [comment]
Here are some thoughts relating to this too: https://ldjam.com/events/ludum-dare/42/rampart/ld42-stats-how-do-you-ensure-your-game-gets-rated

**Comment by local-minimum** [comment]
One thing I didn't think of is if we should have an option to completely opt out of the play/vote/comment part if you're here just to make a game and you don't care about feedback?

**Comment by mikekasprzak** [comment]
I like this. It would be sensible to change the "My Game" link in the top bar to a shortcut to the "Welcome" 
page in the days leading up to the event. This could be an implied URL, i.e. `/events/ludum-dare/44/welcome` that's always there. In general I want to send people to the event homepage more often too (i.e. `/events/ludum-dare/44/`). On my personal TODO is to update the logo at the top of the screen to include to upcoming event number (I'm not sure if there's an open issue for this or not). Mainly I need to find time to sit down and make/cleanup the font for numbers 0-9. These digits would be helpful for making promo banners too.

**Comment by mikekasprzak** [comment]
Moved here https://github.com/LudumDare/ludumdare.com/issues/4.
