### ISSUE TITLE
Remove old commented code

### ISSUE THREAD

**Issue by paulloz** [JammerCore/JammerCore#1757]
This issue is somehow linked to #1755 as it is about cleaning a bit the codebase.  

There's a bunch of places where large or small chunks of old code is just staying here, commented.  
E.g.: [1](https://github.com/ludumdare/ludumdare/blob/master/src/com/dialog/common/common.js#L17-L94), [2](https://github.com/ludumdare/ludumdare/blob/master/src/com/nav-link/link.js#L78-L102), [3](https://github.com/ludumdare/ludumdare/blob/master/src/com/ui/link/link.js#L80-L104), [4](https://github.com/ludumdare/ludumdare/blob/master/src/public-ludumdare.com/main-ld.js#L346-L374), [5](https://github.com/ludumdare/ludumdare/blob/master/src/com/view/bar/bar.js#L129-L133).  

It is unnecessary and contribute largely to make the codebase (which is already quite large) hard to read, especially for new contributors and/or persons who might consider contributing.  
If this is code chunks that are uncommented and used during debug, then `// @ifdef DEBUG` should be used instead of comments. If this is just about not losing old code (*just in case*), then the version control is already here for this purpose.  

I doubt addressing this is something that'll take a lot of time, and it will make the life of newcomers way easier. Obviously, afterwards we need to make sure PRs aren't merged while containing this kind of stuff.

**Comment by local-minimum** [comment]
There are some rare exceptions when we still toggle behavior of the site in code where it may make sense to keep commented code. 

The switch between default feed of active event from smart to danger. But else I totally agree and would love to get rid of it.

There might also be entire classes not used...
