### ISSUE TITLE
Certain game titles break site navigation

### ISSUE THREAD

**Issue by jeremycryan** [JammerCore/JammerCore#1761]
## Unfinished category for LD40

The following is a screenshot from the Ludum Dare 40 submissions, viewing **Unfinished** games by overall rating (https://ldjam.com/events/ludum-dare/40/games/overall/unfinished):

![image](https://user-images.githubusercontent.com/22649301/44940294-97307f80-ad5a-11e8-99a2-454fc75db1a7.png)

## Unfinished "category" for LD41

The following is a screenshot from the same listing preferences for Ludum Dare 41 (https://ldjam.com/events/ludum-dare/41/games/overall/unfinished):

![image](https://user-images.githubusercontent.com/22649301/44940292-88e26380-ad5a-11e8-8394-0d4f5579b879.png)

## Category names are not reserved?

As you can see, a game with Untitled as a *title* occupies the URL that would otherwise be a listing of games in the Unfinished *category*. 

This potentially means that "Jam," "Compo," and "Craft" are also valid game titles, meaning that I could submit an entry titled "Jam" that would occupy the URL for any searches for games within the Jam category.

## The following game names should not be permitted:

- **Jam**
- **Compo**
- **Craft**
- **Unfinished**
- **All**

**Comment by local-minimum** [comment]
That's really weird, because games should not even end up there. They should be at https://ldjam.com/events/ludum-dare/41/unfinished

**Comment by local-minimum** [comment]
The same issue with LD42 btw.

**Comment by mikekasprzak** [comment]
Looks like there's a bug in `/vx/node2/walk`.

https://api.ldjam.com/vx/node2/walk/1/events/ludum-dare/41/games/overall/unfinished?node&parent&superparent&author&pretty

It should have stopped _walking_ by the time it hit `/games`, but alas it tried to continue. I'd guess I put a 'continue;` somewhere instead of a `break;`.

Also yes, `unfinished` should be on the reserved list. I believe the rest are.

**Comment by mikekasprzak** [comment]
Reserve list updated. Turns out they were missing.
