### ISSUE TITLE
Unpublished drafts in main feed

### ISSUE THREAD

**Issue by occultsoftworks** [JammerCore/JammerCore#1772]
Minor bug: Something went wrong when the system rolled over from the Review Phase to the Scoring Phase, and I can see people's unpublished drafts.

![somethingwentwrong](https://user-images.githubusercontent.com/28337733/45054753-e37e0700-b05b-11e8-9903-c99f7c9dbdc3.png)

**Comment by mikekasprzak** [comment]
This isn't specific to this moment. This is a general bug with the feed.

**Comment by zwrawr** [comment]
duplicate of #1407
