### ISSUE TITLE
Links not working on comments

### ISSUE THREAD

**Issue by jasonleekennedy** [JammerCore/JammerCore#1779]
I attempted to link to a youtube video that had some good advice for an issue noted by the original poster, but if I put the link in in a way that the site detects the link, it get 'eaten'.

Post here ->
https://ldjam.com/events/ludum-dare/43/$120986/yeah-guess-im-in

I ended up removing the https:// from the link and it worked. 
Issue happens even when doing 'preview'.

**Comment by jasonleekennedy** [comment]
i was looking through my old posts to see if I wrote anything worth reading before the next LD and found that the youtube link here was also gone:
https://ldjam.com/events/ludum-dare/40/spatium-calorem/post-mortem-spatium-calorem.

I tested using a link to something that wasn't youtube (http://12games12weeks.blogspot.com) and it worked fine.

**Comment by jasonleekennedy** [comment]
notice someone else's post with the same issue, they stated they could see it... appears to be an issue with ABP and the embed.

* Firefox with uBlock Origin - they show up
* Chrome with Ad-block Plus - they don't show up
* Chrome with ABP turned off - they show up.

**Comment by local-minimum** [comment]
There are too many different pieces of embed code in various places of the repo, but from what I can tell it might be

https://github.com/ludumdare/ludumdare/blob/master/src/com/autoembed/smartdomains.js

That the `?` conflicts with another embed code that splits links at `?` to strip away arguments.

**Comment by mikekasprzak** [comment]
Closing this. User was missing the "https:" in the link, which would have triggered embedding.
