### ISSUE TITLE
Game list bad link

### ISSUE THREAD

**Issue by ishanpm** [JammerCore/JammerCore#1785]
When trying to view unfinished games on the current jam, the site will go to this address: https://ldjam.com/events/ludum-dare/43/games/smart/unfinished

However, this will erroneously display the page for a game called "unfinished". There is currently no way on the site to view a list of unfinished games for LD43.

**Comment by zwrawr** [comment]
Looks like this has been fixed.  Going to that like does, in fact, show unfinished games from LD43
![Screenshot from 2019-05-18 22-44-16](https://user-images.githubusercontent.com/18352787/57975328-91e59480-79be-11e9-89c2-dc662a09d35d.png)

And for LD44
![Screenshot from 2019-05-18 22-43-16](https://user-images.githubusercontent.com/18352787/57975319-5e0a6f00-79be-11e9-99eb-7068e77f689e.png)

**Comment by local-minimum** [comment]
Maybe, but if memory serves me right it might depend on if there was a game called "unfinished" or not.

**Comment by mikekasprzak** [comment]
Yes, unfinished is not on the banned name list. I manually renamed a couple
games named unfinished to correct this

**Comment by zwrawr** [comment]
Related to #1761
