### ISSUE TITLE
Cancel Button for Create Account Dialogue Not Working

### ISSUE THREAD

**Issue by occultsoftworks** [JammerCore/JammerCore#1789]
![image](https://user-images.githubusercontent.com/28337733/51699425-b31f1100-1fda-11e9-8c82-a4a0e512982e.png)
The Cancel Button in the Create Account Dialogue Window doesn't appear to work for me. I'm on Chrome.

**Comment by zwrawr** [comment]
This functionality seems to be working on firefox and chrome for me.

It would help if you could retest this and if it's not working provide a screenshot of the developer console ( right click -> inspect -> click on console tab).
