### ISSUE TITLE
Continuously logged out during slaughter

### ISSUE THREAD

**Issue by amymist** [JammerCore/JammerCore#1795]
As I go through the slaughter round, I keep getting a session expired popup. Sometimes it happens after I've taken a break, but not always. Sometimes it's accompanied by another popup saying 'this feature is not currently available,' but not always, and the order those popups appear in vary.

The page refreshes when I close the popup, and I usually do actually get logged out (...but not always), and the page hangs on a message saying "checking login status" until I navigate away. When I log back in, the "Recent Themes" box always shows the same things as the first time this happened, but the numbers and vote distribution graph update to wherever they were before I got logged out. 

This has only happened on the theme page so far, and its only started happening today.

**Comment by zwrawr** [comment]
Can you open the developer console in your browser and see if there any error messages in the console.

To open this right click -> inspect then click on the console tab. Any errors should be in red text, screenshots of the these would be useful.

**Comment by amymist** [comment]
![1](https://user-images.githubusercontent.com/2464787/56462988-01953f00-6381-11e9-9d00-62979cda6e9e.png)
![2](https://user-images.githubusercontent.com/2464787/56462998-1eca0d80-6381-11e9-9a9d-3cb5edf70b04.png)
First image is when the sessions expired popup first appears, second is after hitting ok. Didn't get the 'this feature is not available' popup, but I'll keep an eye out for it, and add it if it comes up again.

**Comment by amymist** [comment]
![3](https://user-images.githubusercontent.com/2464787/56465152-ffe17080-63ac-11e9-9530-b1f2ee82ddaa.png)
As promised.

**Comment by mikekasprzak** [comment]
Something to try, logging in to the insecure (HTTP) version of the website. You'll need to use this special URL: http://ldjam.com/?insecure=1

Hopefully that's enough to get it working. Alternatively, as annoying as this sounds, you can try using the website in incognito mode. I remember hearing folks having success with that.

It's been a while, but I think these sort of issues tend to relate to cookie handling by the browser or a 3rd party extension, plugin, or security software (Norton, AVG, Avast, etc) you have installed.

**Comment by mikekasprzak** [comment]
This should be resolved.
