### ISSUE TITLE
Slaughter Round: Page is presenting themes already voted on

### ISSUE THREAD

**Issue by tustin2121** [JammerCore/JammerCore#1833]
When attempting to slaughter this year's almost 4000 themes, I've noted many times I've been seeing the same theme multiple times come up for a vote. For example, "All about perspective" (35229) showed up at least three times that I can remember. I think I've voted on like 20 themes with "gravity" in the name, despite there being only 6 themes mentioning gravity. And I *know* I voted on the theme "It's not a bug, it's a feature" (37399) twice. This is over the course of like 6 or 7 sessions (between getting logged out and reloading to make sure I wasn't logged out in the middle). I was surprised at how few duplicates there were when I opened up the JSON and looked, because I swear I was getting multiple duplicates of the same theme.

This also implies that I'm now incapable of actually looking through ALL the themes, because the page keeps counting upwards despite basically re-voting on the same themes multiple times.

What baffles me is that the recent themes list apparently knows which themes I haven't voted on yet, as it doesn't show those themes, but the code that selects which theme to vote on next doesn't check if it's been eliminated from the listing? Or perhaps the already voted on themes aren't being filtered out of the collection of themes that need to be voted on when the page first loads?

**Comment by A-312** [comment]
Me too.

 - `Theme`, `theme`, `theme.`
 - `word1 and word2`, `word2 and word1`

**Comment by mikekasprzak** [comment]
My apologies. I have a script that removes duplicates, but I forgot to run
it. Doh!

Ran it on Wednesday, and it removed about 1000 themes. There's a small
chance you will see one you have voted on, but it should only be once more.

>

**Comment by A-312** [comment]
@mikekasprzak Also, if did today ?
