### ISSUE TITLE
CORE: Automation

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#185]

**Comment by povrazor** [comment]
State machine is working, but it will be cranked along manually this time, for safety's sake.

**Comment by povrazor** [comment]
Again, not actually in development, but the hooks are in place to be.

Mode of an event is controlled by the Metadata. It increments through to distinct states to change the vote mode and whatnot.

The only downside (?) is that some tasks do take time, and metadata does gets cached by the Node Cache. I don't want to thrash the state tables either, setting a global state when doing jobs. I also don't want to globally disable the entire site while performing jobs, but something needs to happen.

This may mean API calls need to return a "busy" state, and handle that correctly (knowing to retry **exponentially** after a second).
