### ISSUE TITLE
Site doesn't recognize failed attempts at loading comments

### ISSUE THREAD

**Issue by local-minimum** [JammerCore/JammerCore#1890]
This related to #1887, but specifically when loading comments fail there's no way for the user to re-attempt loading it. You get stuck with the spinner unless you manually empty your cache.

Expected behavior:

If the initial request times out or fails, that response shouldn't be cached / a simple reload should re-attempt getting comments.

**Comment by local-minimum** [comment]
Just now (activity shouldn't be too high at this hour) on a page with 25 comments, I had to empty cache and reload about 5 times before I got to see them.

**Comment by winniehell** [comment]
This is how the described behavior looks like:

![Bildschirmfoto vom 2020-09-26 17-11-02](https://user-images.githubusercontent.com/1652293/94343874-8fb43100-001b-11eb-8967-c84899a22d41.png)

(spinner is hidden behind white box)

Retrying should probably happen here: https://github.com/ludumdare/ludumdare/blob/71434301f8739464fa29a8e7d536fbf90ac58475/src/com/content-comments/comments.js#L102-L104

**Comment by mikekasprzak** [comment]
Resolve by #1927
