### ISSUE TITLE
Is there any way to change one's username?

### ISSUE THREAD

**Issue by ElnuDev** [JammerCore/JammerCore#1905]

**Comment by AnimeGeek32** [comment]
Yeah, I want to change my username too.

**Comment by ElnuDev** [comment]
Maybe I'm an idiot and missed it, but being able to change one's password would be nice as well!

**Comment by local-minimum** [comment]
It's been a while since I contributed to the code, but I think the answer is unfortunately no as the #1621 is still open

**Comment by mikekasprzak** [comment]
Send me an email with your username (current, desired) and I can take care
of it for you. As for passwords, the one workaround is logging out and
doing a password reset instead of logging in.

**Comment by ElnuDev** [comment]
Sorry for the late reply, but where can I find your email? I must have missed it somewhere. Thanks!

**Comment by ElnuDev** [comment]
https://ldjam.com/contact/

**Comment by mikekasprzak** [comment]
#1621
