### ISSUE TITLE
Iframe HTML5 games[Suggestion]

### ISSUE THREAD

**Issue by honzapatCZ** [JammerCore/JammerCore#1909]
Good idea?

**Comment by mikekasprzak** [comment]
There are a variety of security implications that have held us back from
doing this. We did have support this on the old website, but we were less
security conscious back then.

**Comment by honzapatCZ** [comment]
But you arent against the idea? I could look into it. If Iam not mistaken iFrame can be setup as full sandbox.

**Comment by mikekasprzak** [comment]
Against no, but it's more than just adding an iframe. There are
implications we need to consider when working with Itch and Newgrounds, the
later features advertising which is something we don't have well defined
policies on. It would have to be HTTPS only, which not everybody
understands how to set up. There was also a complicated security problem I
was alerted to a few years back that we are currently sidestepping by
heavily restricting how embedding works (uploaded images and YouTube only).
I'm not familiar with all the details off the top of my head, but it had
something to do with the fact that we handle logins via JavaScript fetch
requests.

This is something I want to revisit some day though.

Mike Kasprzak

**Comment by honzapatCZ** [comment]
Can you send me more details about the security problem?
As W3 states `<iframe src="demo_iframe_sandbox.htm" sandbox></iframe>` sandbox should instruct the browser to treat the iframe as completely separate webpage, with no access to the parent page.

**Comment by mikekasprzak** [comment]
Closing for #2050. Embedding games is on the roadmap now, but only via games uploaded to our server.
