### ISSUE TITLE
Branding: Logo, Typeface, and Guide

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#194]
Since it's public now, I can finally add this sneak peek:

![ld-type](https://cloud.githubusercontent.com/assets/1570313/17820411/c01fdca8-661a-11e6-88d7-40ba3317df66.png)

https://twitter.com/mikekasprzak/status/766696603898023937

Post the branding guide, when it's finalized.

**Comment by povrazor** [comment]
Include a set of numbers too, since it's common for people to photoshop-together specific images. I'm guessing the original font (Null by FontFabric) will have a few things that disagree with my changed aesthetic (no fashion gaps).

**Comment by povrazor** [comment]
Some suggestions from twitter:

https://twitter.com/Pitzik4/status/766709305743552512

https://twitter.com/battlecoder/status/766709241772122113

and a joke

https://twitter.com/BrendenCameron/status/766700935074701312

**Comment by povrazor** [comment]
![phatterlogo](https://cloud.githubusercontent.com/assets/1570313/17822555/c7ffa862-6625-11e6-8894-4e89c7815337.png)

![phatter-ld](https://cloud.githubusercontent.com/assets/1570313/17822560/cb2e00e2-6625-11e6-8bc5-0e70ddcd5f65.png)

**Comment by povrazor** [comment]
![jampairs](https://cloud.githubusercontent.com/assets/1570313/17823380/2cc8bd3e-662a-11e6-878d-698b99dd504f.png)

**Comment by povrazor** [comment]
![final-tweaks](https://cloud.githubusercontent.com/assets/1570313/17824007/6b852b7c-662d-11e6-91ed-d5a01ddfa651.png)

Just a few final'ish tweaks. Rounder inside of the R. Flattened the side of the E.

**Comment by povrazor** [comment]
Update this with correct color scheme, and numbers... and an actual download.

**Comment by povrazor** [comment]
For those that can't wait, you can get SVG's here (without colors).

https://github.com/ludumdare/ludumdare/tree/master/src/icons/ludumdare

**Comment by povrazor** [comment]
Add a link to the branding guidelines on the source code page (once they exist).

Probably a WIKI page here on GitHub.

**Comment by local-minimum** [comment]
It seems to me that this should not so much be an issue as part of the wiki.

**Comment by povrazor** [comment]
This is an issue because it's not finished. ;)

**Comment by sgstair** [comment]
Also note for future reference color use has since changed
