### ISSUE TITLE
Blog post issues on Chrome and Firefox

### ISSUE THREAD

**Issue by gamepopper** [JammerCore/JammerCore#1954]
On Firefox (Version 92.0.1 (64-bit)):
- New/Edit Post
- Click the title field and enter title - Works
- Click the description field and enter post content - Selects but immediately disables, preventing me from writing text.

![GIF](https://user-images.githubusercontent.com/6163825/135356650-90411f0c-3229-443e-b6e9-e160e581d900.gif)

On Google Chrome (Version 94.0.4606.61):
- New Post
- Click the title field and enter title - Works
- Click the description field and enter post content - Works
- Publish - Goes straight to unpublished draft.

![image](https://user-images.githubusercontent.com/6163825/135356714-05bdd859-c2c8-42b7-bb7b-36acd10aa977.png)

The Chrome issue I can manage, but it caused me to double post my blog and there is no way for a user to remove one of their posts.

![image](https://user-images.githubusercontent.com/6163825/135356684-de63b42a-b286-4c37-ac46-d4b8984343d4.png)

**Comment by CowboyBebop** [comment]
Same here

**Comment by CowboyBebop** [comment]
The best you can do atm is write it elsewhere and copy-paste in

**Comment by mikekasprzak** [comment]
Strange. I'm running Firefox 92 on this PC, and I wrote many of the news posts here. Not sure why you're losing focus. Do you have any Firefox addons of note?

The "unpublished draft" issue is something we call the caching bug. Your post successfully posted, but the page cache stored the old unedited copy of your post instead of your new one.

@CowboyBebop Which issue are you having? Double posting or firefox losing focus?

**Comment by zwrawr** [comment]
Do you use Grammarly or anything that rewrites text in place?
Could you `right click -> inspect -> console` and copy/screenshot what it says?

**Comment by zwrawr** [comment]
![Screenshot from 2021-10-03 23-00-39](https://user-images.githubusercontent.com/18352787/135772890-0b91df1f-010e-46dc-b28a-860400dc0ea8.png)
![Screenshot from 2021-10-03 21-43-39](https://user-images.githubusercontent.com/18352787/135772893-573e7ea0-7370-4ed4-a892-b7a83414b473.png)

**Comment by mikekasprzak** [comment]
Closing this in leu of #1973.
