### ISSUE TITLE
Allow opting out of voting entirely.

### ISSUE THREAD

**Issue by local-minimum** [JammerCore/JammerCore#1965]
I came across this entry https://ldjam.com/events/ludum-dare/49/survive-phantom-estate that expressed that they didn't want to receive votes.

I think it would be nice if we allowed an opt-out of voting entirely (only receive comments).

I'm not sure how to list those games, but perhaps list them in an own category and not include them in any of the classic, smart, danger etc categories?

There could be quite a few of those who have very few votes who really only where participating to make the game and feel they achieved that, and it would help voting in general if they could be separated out.

**Comment by mikekasprzak** [comment]
There's a category "Unfinished" that does this.

**Comment by mikekasprzak** [comment]
Resolved by Encore support #1979.
