### ISSUE TITLE
Site reachable, however remains loading and unable to fetch content

### ISSUE THREAD

**Issue by Tgill1085** [JammerCore/JammerCore#2072]
Hey there! Sorry to reach out this way, however we didn't see anything pop up on Twitter or Reddit, and wanted to make sure you were aware of an issue with the ldjam.com website. I'll be providing a screenshot with this post that shows what we see when we attempt to visit the page, however a brief description includes that the site is reachable, but unable to load and display content other than the timer for the jam, and the live stream from twitch on the side bar. Other pages such as LudumDare.com/help show as a 404. When attempting to use the login form, and providing credentials for the account to log in, the site returns with an error message that states "ERROR". Hopefully these details help in resolving the issue, and thank you for your time!
![ldjam_down](https://user-images.githubusercontent.com/90009988/158489344-253e5555-ced4-486b-9015-368e1cf2c9c2.png)
![ldjam_error](https://user-images.githubusercontent.com/90009988/158489346-9334e2e5-4c18-4a0a-a848-7d7c32ea826d.png)

**Comment by mikekasprzak** [comment]
Oops! That's embarassing. The one day I don't check social media is the day this happens. 

Anyway, this should be fixed now.
