### ISSUE TITLE
Content doesn’t load (expired/invalid certificate for api.ldjam.com)

### ISSUE THREAD

**Issue by daprice** [JammerCore/JammerCore#2086]
Apologies if you already know about this. ldjam.com loads but no content shows up; the console log says the certificate for api.ldjam.com is invalid. Attempting to load an API URL directly shows that it’s trying to use a certificate for static.jam.vg that expired in 2017.
<img width="896" alt="static.jam.vg Issued by: Let's Encrypt Authority X3 Expired: Sunday, July 9, 2017 at 5:13:00 AM Central Daylight Time “Let's Encrypt Authority X3” certificate is not trusted" src="https://user-images.githubusercontent.com/3615519/158923781-5d1b079d-6d27-4585-b6e1-732fabc10baf.png">

**Comment by mikekasprzak** [comment]
Oops! Yeah I was cleaning up some of the server configurations and I accidentally reverted to an old certificate. Should be fixed now.
