### ISSUE TITLE
API: Is there a way to get all theme suggestions entered into Slaughter?

### ISSUE THREAD

**Issue by outfrost** [JammerCore/JammerCore#2097]
I wanted to grab the list of all theme suggestions that were part of the Slaughter for LD50, compare it against my Slaughter votes, and see a list of those that I approved of (see [gist](https://gist.github.com/outfrost/cbfd51cdcee3f9136b260befdf7730a0)).

I can get the list of my Slaughter votes from `/vx/theme/idea/vote/getmy/276397`, but I can't seem to find an endpoint that would show me the text of those ideas. Is it still available? Could it be made available?

There were some neat ones in there that my forgetful brain just wanted to save for later inspiration :)

**Comment by mikekasprzak** [comment]
Yes there is. I'm afraid I don't have the endpoint handy (I'm on my phone),
but the Theme Slaughter uses the same endpoint to download everything at
once. Off the top of my head, I think it might be `/idea/get` instead of
`/idea/vote/getmy`, and you pass the ID of the event.

**Comment by mikekasprzak** [comment]
To find out for sure, ghe endpoint source code should be in
`/public-api/vx/theme.php`. I believe that's one of the older API endpoints
with the large nested IF blocks, so it may not be as concise and easy to
browse, but there will be comments describing what each endpoint looks like
from the outside. Scroll down until you get to the "idea" section, and it
will be something under that. I don't think it's under the `vote`
subcategory.

**Comment by outfrost** [comment]
I previously looked at `/theme/idea/get`, which is commented out and returns a 403, but this time I looked again and noticed `/theme/idea/vote/get`, which seems to be what I was looking for. Indeed, `/vx/theme/idea/vote/get/276397` returns the suggestions in LD50 Slaughter.

Thanks! :)

**Comment by mikekasprzak** [comment]
Great, I'm glad you found it.
