### ISSUE TITLE
Servers: Upgrade to Ubuntu 18.04 LTS (i.e. format and reinstall)

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#215]
Just to keep things current, upgrade the servers to Ubuntu 16.04.

I did try manually upgrading some weeks ago, but I ran in to issues (they didn't take).

It makes total sense that we do it **BEFORE** we permanently switch to the new website, just to keep things current.

**Comment by povrazor** [comment]
Decided to defer this. Was able to switch to the latest Linux kernels even without switching Ubuntu versions. Hoping an update will work later. Fresh would have been nice, but no time left.

**Comment by mikekasprzak** [comment]
This needs to to happen. Ubuntu 14 expires end-of-the-year. 18.04 is fully capable of running everything but search right now.
