### ISSUE TITLE
theme suggests on pale moon

### ISSUE THREAD

**Issue by Brian151** [JammerCore/JammerCore#2155]
i did my occassional check to see when the next ludum dare will be, and noticed it's a biiit sooner than i had thought. so, i went to post my suggestions, and the textbox is not working. this only affects pale moon. my current version is 31.2.0.1 64 bit and i'm using windows 10 as an OS.

no matter how much i try to type, nothing is input
no errors in the browser console, either

**Comment by mikekasprzak** [comment]
I can confirm this is reproducible on Pale Moon, which if I'm honest I'd never heard of until today. :sweat_smile: As for the specific problem, it does appear to be a nuance of how Goanna/Pale Moon handles keyboard events compared to Chromium, Webkit, and (recent) Gekko based browsers. The code in question is nearly 6 years old, so it's quite peculiar that it works everywhere expect Pale Moon. :thinking: 

I would recommend making your theme suggestions using a different browser, or the browser on your phone. In my very quick test, the rest of the website does appear to work fine, but your mileage may vary.

If I'm honest, Pale Moon probably wont be a browser we will officially support. I may keep it around for occasional testing (I need to try out the Adobe Flash support), but it's more a novelty than anything. According to [Wikipedia](https://en.wikipedia.org/wiki/Pale_Moon) the current version is based on a **5 year old** fork of Gekko. Now that Internet Explorer is dead, I've been itching to use browser features from the past half-decade. :wink:

**Comment by Brian151** [comment]
yeh, strange for sure

i forgot how it was i learned about it. a friend, iirc? and basically came down to how mozilla basically betrayed its userbase and the entire internet. i already use firefox for some sites, and a select few webgl games still demand a chromium browser >.< .

how may flash-based submissions are still posted? thought almost everyone was finally bullied out of making them. there's also ruffle if not having AS3 is an acceptable compromise [for the time being].

honestly, the tech of the past half-decade and beyond is so much more sane. flash arose of necessity, HTML5 and "modern web" has always primarily served to fill the agenda of Big Tech [or copyreich, in case of EME] while pretending to offer anything meaningful. Parts that actually would've been useful were implemented half-baked and/or with critical flaws. 

thanks anyways!

**Comment by mikekasprzak** [comment]
> how may flash-based submissions are still posted?

None, but one of our Keynote's was made in Flash. On my TODO list is to eventually capture a lets-play of that original keynote, so folks can watch it again. I assumed I would need a Windows XP VM (or something like it), but this might be an option. :thinking:

**Comment by Brian151** [comment]
ah, dang... submitting it to flashpoint might also be an option. provided, that's a hefty download for people and i'm scared to know what duct tape and black magic holds that together...XD 

in the future, i plan to derive a format from SWF and use that with native/"native" code of $platform. won't be quite the same, i already plan to make a few changes deliberately to render it incompatible with flash player. though, ironically considered compiling a loader in AS3 for those massochists out there. 

well, good luck with your stuff.
as another suggestion, check the open source flash repo. readme has basically all the flash preservation stuff linked together :P

**Comment by mikekasprzak** [comment]
Thanks for the tip. When I finally get around to capturing the game I will.
