### ISSUE TITLE
Write a "History of me and Ludum Dare" piece

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#217]
I seem to get requests for interviews rather often. Some are from websites/blogs, some from media/newspapers, some are podcasts/youtube shows, and some are students doing school projects. The last one is what inspired this.

Rather than being the jerk that doesn't answer his interview e-mail requests (as I tend to be), I should just "publish" an extended article talking about all these things, all the usual questions about our history, whose involved, etc. That way I can just point people that make interview requests to it, and have them mail me any other questions they have. 

'cause I repeat myself a lot. ;)

**Comment by povrazor** [comment]
This is started. https://ldjam.com/history
