### ISSUE TITLE
Link to game not showing.

### ISSUE THREAD

**Issue by local-minimum** [JammerCore/JammerCore#2188]
I wanted to host my html game on itch, but that was the only link I needed and it refused to show the link unless I added a second link.

https://ldjam.com/events/ludum-dare/51/pumpkinz

**Comment by mikekasprzak** [comment]
Very strange. I don't think the code has changed at all, so I'm not sure why it suddenly needs a dummy link for links to work. 🤔

**Comment by local-minimum** [comment]
Could it be that there's a bit delay on cache invalidation or something?

**Comment by mikekasprzak** [comment]
Fixed in #2198. :man_facepalming:
