### ISSUE TITLE
Games that have opted out of rankings still show up in the smart and classic feeds

### ISSUE THREAD

**Issue by EthanPlant** [JammerCore/JammerCore#2201]
[This game](https://ldjam.com/events/ludum-dare/51/sonar) is currently near the top of both the smart and all classic feeds, the problem is since this game cannot receive any ratings, its smart or classic scores can never go down. This could potentially create the situation where the smart or classic feeds are dominated by games that have opted out of ratings.

**Comment by mikekasprzak** [comment]
Fixed in #2202. Authors of Sonar have corrected the flag (turned off by mistake). They should begin falling off the page.
