### ISSUE TITLE
Theme Slaughter: Previous Theme order is messed up after refresh (was List of past votes stopped updating)

### ISSUE THREAD

**Issue by CyberStarLight** [JammerCore/JammerCore#332]
At around 550 votes my theme list stopped adding the new votes. I investigated a bit in the firefox inspector, the vote goes through and I get a response of code 200(OK), and the count of the total votes go up.
but the list of text themes stays the same. when refreshing the page, or even after logging in again.

I'm not sure if my votes are added properly to the database or not.

I looked at the request/response for the list, and it attempts to send all of the 500+ votes names and yes/no. but the new votes are not there. maybe it's trying to send too much?
I guess you could just send the last ~10 votes or so, as all of them don't show anyway. in case it's just a display issue.

**Comment by povrazor** [comment]
Can I get you to add a couple more votes?

I'm seeing 572 suggestions in the database under your ID (761).

**Comment by CyberStarLight** [comment]
You seem to be right, and it's just an ordering issue. I voted again for "Mom's spaghetti", the visible list was not updated but I found it in the response text (after a refresh): as "3626":"Mom's spaghetti". so it does get to the browser, just not displayed.

**Comment by povrazor** [comment]
Cool. So it's the screwy way I fetch the list of previous themes that's to blame.
