### ISSUE TITLE
Investigate making our own version of TestFlight (iOS testing)

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#336]
Since Apple takes a very long time to publish games, investigate if it's possible to make our own TestFlight.

For those that don't remember it, TestFlight was a 3rd party service that let you create a beta testers list. It's now owned and operated by Apple, but I do wonder if the hooks are still in place for creating a 3rd party one.

I don't know what the limits are. I seem to remember there being a 100 user limit for something (Free iOS codes?). But I want to say at some point a limit jumped to 1000. I don't know though.

So ideally, assuming we can make certificates that sign for 1000 devices (or whatever the max is), we could let users add up to 2 (?) iOS devices to their Jammer account. We then generate a certificate for every 1000 devices, and let users upload signed binaries to our version of TestFlight, one per group.

Having to make many group builds could potentially become a pain, so as part of the event signup process, you should have to mark your iOS devices as "not stale". When a device goes stale, it's slot is freed up for devices that haven't been assigned to a group.

When downloading, we'll have to make the groups your devices belong to obvious (or even not show groups you don't have).

Ideally, I would like us to reach an equilibrium where there's only 2 certificates (or best case, just 1).

**Comment by povrazor** [comment]
According to http://appreviewtimes.com/, review times are down to about 2 days. But with the holidays coming up, it's already up to 4 days.

So surprisingly, it might be viable to do iOS without our own testing platform. It's just to suck for December events.
