### ISSUE TITLE
Theme Suggestions: Information/Guidance Page

### ISSUE THREAD

**Issue by karai17** [JammerCore/JammerCore#346]
Right now there is no guidance for users submitting themes on what constitutes a "good" theme suggestion. In my humble opinion, I believe a theme should not dictate what kind of game you can make, nor should it dictate what you *can't* make. A theme should guide you in a general direction--but not too general! I've been slogging through the theme slaughter over the past few days and I have a few suggestions:

1. **Mechanics are not themes**: "you control time", "game about jumping", "light and shadows" are not themes, they are mechanics. These suggestions tend to force you in a direction. Would we be happy if there were 3500 games that were all based on the same mechanic? Bleh!

1. **Genres are not themes**: "fps", "platformer", "open world survival horror mmo" are types of games, and not everyone wants to make one of those. The beauty of Ludum Dare is that output is so diverse. Limiting people to making the same game with a different skin would be unfortunate.

1. **Constraints are not themes**: "2d", "8-bit", "128x128" are limitations and provide no guidance for the user to make a game, only constrain what they are allowed to make.

1. **One word themes are worthless**: Themes that consist of a single word are not useful. They are extremely vague and unimaginative. I would definitely outright block single word submissions.

1. **Ultra-specific themes are too personal**: If someone really wants to make a specific game, they should be encouraged to do so! But they should not limit everyone else to make that game too.

In general, I find themes that are 3-5 words in length to be ideal. Less than that and they tend to suck. Above that and they become too personal. As it stands right now, my "Yes" rate is between 1 and 2%. If users were given more guidance and if really bad themes were outright blocked, we might be able to bring that up to 5 or 10%, which would be *awesome*!

**Comment by karai17** [comment]
Also worth mentioning, reminding people to make sure that their themes are spelled correctly and have proper grammar (if applicable) would be good too. There are a lot of themes (including LD36's final theme...) that have typos or spelling mistakes. I might be picky, but that really turns me off of a theme, even if the theme was otherwise good.

**Comment by povrazor** [comment]
I don't necessarily think an article will help with the bad suggestions, but I'm certainly open to having a _best practices_ guide when it comes to making suggestions and Theme Selection.

Sometimes quotes do work well. "It's dangerous to go alone. Take this" I think was a good one. For those that get the reference, it clicks. For those that don't, okay, we need to work a little harder to explain it.

I would want to be sure that care is taken in writing this piece. I know there's an opinion that themes like "light and shadow" are not good themes, but there's still a lot of breadth there. Even "you have to jump" has a lot of breadth. Choice of words and grammar really affects the flexibility and the likability of themes. So to actually see certain ideas ("Everything on one screen"), a less desirable wording is sometimes necessary.

**Comment by balohmatevz** [comment]
There are two mindsets on themes, and this only represents one of them. While "theme-first" or "mechanics-first" are two different approaches to game design, the use of the word "theme" in regard to game jams does not necessarily refer to the same kind of theme as in theme-first game design. 

A game jam's theme can be any of what you wrote on your list of themes you find invalid, and has been in the past. I completely disagree with any attempt to limit what themes can be - that's what the slaughter and voting processes are for. The Ludum Dare community has previously selected constraints as the theme: "entire game on one screen" and "two button controls" come to mind. Considering this seems to happen somewhat frequently, I really don't think anyone can claim these themes as invalid.

**Comment by povrazor** [comment]
I too wish spelling went better, but sometimes the mistakes are pretty fun. :smile:

https://twitter.com/cynicalmonkey/status/804356808391458816

**Comment by karai17** [comment]
@balohmatevz The problem is that those aren't themes. They tell you, very specifically, what you can and cannot do. I agree with @povrazor that themes should be inspiring, and those don't really "inspire" so much as direct. Of course any theme can be abstracted away form the words themselves (light and dark could mean good and bad, night and day, happy and sad, etc) but it is severely limiting.

I much prefer open-ended themes that simply give you a nudge. Some examples that I like are:

* And then there were two: Two what? What happened before there were two? Are we counting down or up?

* Not as it seems: What isn't? what did it seem to be? Is it good or bad that it is different?

**Comment by balohmatevz** [comment]
That's your preference, which is perfectly fine, however it's not universally shared by all LD participants, as evidenced by such themes sometimes becoming the jam theme. Having a preference is fine. I have a preference for theme types too. I however disagree with prescribing your (or my) preference as the one true type of theme for Ludum Dare.

**Comment by povrazor** [comment]
I'm glad I have you both here discussing this. This basically sums up why I think care is important when writing the guide. :smile:

**Comment by povrazor** [comment]
I do think your 2nd and 3rd points @karai17 are correct. But after those, that's when the debate starts.

**Comment by povrazor** [comment]
I think context does help. Understanding you're asking thousands of people to make a game based on the suggestion you're making. No theme is perfect, and we can't always guess the potential of a theme, but we can do a better job making the scope better understood.

**Comment by karai17** [comment]
@balohmatevz Well sure, as I said in my OP, these are just my suggestions. I think it's ok if Ludum Dare has an opinion about what sort of themes are better than others. My issue with limitations is that it could exclude a lot of people from participating. For instance, what if the "2d" theme wins? Suddenly a significant chunk of people are disenfranchised from participating because their skills are with Unity or Unreal. I personally make 3d games so I probably wouldn't participate. That also excludes people from making text-based games, VR games, card games... No good!

@povrazor Yeah, I really think my 2nd and 3rd points are spot on. I also think my 1st point is too. 4 and 5 are definitely opinionated, though I strongly believe in 4. If the theme is 1 word, I click No.

**Comment by karai17** [comment]
@povrazor Exactly my point with suggestion 5, themes that are ultra-specific probably come form people who forget that they are asking thousands of others to make the exact same game they want to make. If you want to make that game, go make it! :D

**Comment by balohmatevz** [comment]
Personally I think the system works well currently. It's how I'd design it if I was building it from scratch. Open suggestions -> Rough quality evaluation (slaughter) -> Manual inspection of top themes -> Sufficiency voting (aka "which themes are you fine with?"). The one labour-intensive task could be simplified by reducing the number of themes that are selected for voting from 80 down to 20, which likely wouldn't reduce the average selected theme's quality. 

Also, Ludum Dare can have opinions, but I don't think it should have an opinion on this. It should offload this particular choice to those who will be stuck with the outcome (in this case the theme). The slaughter and vote ensure this. If plurality or majority voting consistently starts overruling or disqualifying a minority, then I will agree that a solution is needed, however I'm not in favour of introducing rules or guidelines for theoretic problems until they show themselves in practice. This just leads to rule creep, which I don't want, especially when what we have is a free and open system, which currently works fine.

**Comment by povrazor** [comment]
> Also, Ludum Dare can have opinions
Haha, if there's one thing Ludum Dare has, it's that. :laughing:

**Comment by karai17** [comment]
It's a bit of a running joke that LD theme suggestions suck. It's also disheartening to slog through thousands of themes in the slaughter only to click "yes" once every few minutes. I would be all for reducing themes that enter the slaughter if that meant the general quality went up. I bet cutting 1-word themes from the slaughter would reduce the total themes by a third. Or if users were advised or enforced to submit 2+ word themes, the number of themes would be about the same but the general quality would go up.

**Comment by povrazor** [comment]
I'm hoping my new round fixes some of the concerns (sadly, I don't have enough time to get it in for this event). The Slaughter itself is a broadphase. It's there to cut the list in half (or more). Pre-slaughtering the slaughter is a bit redundant. ;)

**Comment by balohmatevz** [comment]
Again, several winning themes were single word themes. "shapeshift", "growing" and "minimalism", for example. From the slaughtering I've done, I voted up about 40% of viewed themes. Yes, there were some dumb ones in there, but if you only vote up once every few minutes, then your expectations may be way too high or you might be looking for something incredibly specific. In any case, I don't think it's the process or the suggested themes that are at fault there.

**Comment by karai17** [comment]
I will admit that I am a bit picky when it comes to themes, but I don't think I am completely off base here. Perhaps enforcement isn't necessary, but guidelines, even if opinionated, would be a huge help to quality.

**Comment by balohmatevz** [comment]
If you'd like a larger sample size, take a look at the 84 one hour game jam themes: http://onehourgamejam.com/ . Everything after jam 40ish was selected in a similar way to Ludum Dare, where anyone can suggest themes, these are then voted on in an "I'm fine with it" way and the most supported one is the jam's theme. You'll find lots of mechanics and constraints in the list, and it worked fine.

**Comment by eLeit** [comment]
I agree with 1-3 and 5. But I actually think one word themes are less specific than a phrase of some sort. There are of course single words that "make no sense" but a single word can be quite abstract and therefore allow people to translate it however they want. I usually find phrases more confining because they are more specific. Most of the themes I like are one word which inspires me in some way but doesn't limit me to a certain type of game or a specific mechanic. I hate themes that enforces 1-2 buttons only or 1 screen only because that limits my options.

**Comment by scriptorum** [comment]
I don't have a problem with constraints for themes except that they're so _common_. I worry about games coming out too similar. People must like the challenge of meeting these constrained themes for them to keep rising to the top. I prefer more abstract prompts like idioms.
