### ISSUE TITLE
Core: Permissions

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#416]
Store permissions in a user's `protected` meta data.

**Comment by povrazor** [comment]
Specific permissions could be implemented as meta links.

For added safety, hashes could be stored in `private` data (of both), and must match for "hashed permissions" to be valid.

**Comment by povrazor** [comment]
Metadata and Links are stored at different permission levels now. Currently, users only have permission to edit specific public metadata. For security reasons this should probably stay the case. Other metadata and links should be managed by other API calls... ?

**Comment by mikekasprzak** [comment]
I need to review this, but this might be done.
