### ISSUE TITLE
"The Compo" as the Open Source/Creative Commons event

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#477]
The **COMPO** is confusing. Way too much time is spent trying to explain the nuances of what you can and can-not use in it. This new world of paid Unity Assets has really messed things up.

I want to simplify this.

Key things:
* Creators keep their rights (no GPL)
* Work is released in to the public domain for others to learn from, not because it is abandoned
* Permission is given to transform, but the original belongs to the creator

Basically, what I want a **Creative Commons** license for **COMPO** games. That's not the typical license associated with things containing source code, but what's being released is a work (a game), not a library for process X or Y.

The legalese of the **COMPO** would change to include both source code and assets (was just source code). So yes, while we do live in a world of Unity Store assets now, the license agreement for those assets probably doesn't allow you to share them publicly like this.

If you want to use them, enter the **JAM**.

**Comment by scriptorum** [comment]
I'm fine with a Creative Commons license as long as authors can choose to be less restrictive if they want (BY/SA/NC/ND). I also like that the license should cover assets.

I find the current rules on what you can use confusing. Once you allow paid assets with a "but" it gets harder to communicate; the clarifications I've heard seem to contradict the rules page. If this becomes an "open source event" and shuts out paid assets completely, I'd be okay with that. It's easiest to grok, and also it sets a good community tone. If you made the goal _anyone can compile and run your project for free_ that would eliminate, say, commercial game frameworks that don't have an indie tier. But these days that's a shrinking list.

**Comment by povrazor** [comment]
That's always been the case for the Compo: you need to make it from scratch, but you can use Middleware and (code) libraries. It got messy because "Asset" in Unity-land covers code, libraries, in addition to content.

Anyway, the point of the CC talk was that I'm really getting sick of Indie's getting ripped off for open sourcing. And yes, being able to choose a license is super-important. But if you don't choose one, I think defaulting to something that protects the creator instead of being outright "public domain" is best.

**Comment by scriptorum** [comment]
Gah! I've been infected by Unity too, since all this time I've been just talking about source code.

**Comment by local-minimum** [comment]
I'm for a very short condensed "This is what COMPO is" and then it would be a nice "This is fine" and "If you do this, then you should enter the JAM".

To the "This is fine":
* to have someone play test your game. In fact please do. It is dead hard to make a good game without anyone checking if it makes sense to them too.
