### ISSUE TITLE
Data Website: Publish Slaughter Data

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#50]
Set up some scripts for generating JSON dumps of theme slaughter data.
- Theme List (with Ids)
- Anonymous Theme Votes (i.e. without UserIDs)

Publish them to: data.ludumdare.com

**Comment by povrazor** [comment]
Stub website is up.

http://data.ludumdare.com

There is no data though.

I'm undecided if there should be a separate repository for the data. Probably. Yes. Definitely.

Okay it's decided. I'll do it later though.

**Comment by povrazor** [comment]
Okay, I've decided the data website should just be instead:

https://github.com/ludumdare/data

When I get a chance, I'll kill the current data website setup, and reconfigure the domains to redirect to GitHub. 'cause really, there's no reason to make a separate website for it. It'll be simpler just to maintain a repo. No need to edit lists, just give files good names.

**Comment by JanWerder** [comment]
Maybe it could be automated with a Library like https://github.com/kbjr/Git.php
So after the Slaugther end, the site automatically pushes the latest data to the git repo

**Comment by povrazor** [comment]
Ya, something like that. Just need to create a robot user and configure his permissions accordingly.
