### ISSUE TITLE
Calender: Has 30 days in December, not 31

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#500]
Yay. This is getting silly.

**Comment by Aurel300** [comment]
Isn't this fixed?

![screen shot 2017-04-16 at 18 15 46](https://cloud.githubusercontent.com/assets/1102162/25072841/c69b0ea4-22d0-11e7-873c-f4fba111c306.png)

**Comment by povrazor** [comment]
It's not December. ;)

**Comment by Aurel300** [comment]
It's not the 31st either. I set the Date to `new Date("2016-12-31")` in the above screenshot, tried a bunch of dates in December around that, also in 2017.

**Comment by povrazor** [comment]
Oh, then I might have been seeing things. :wink:

Honestly LD37 was a bit of a blur. :tired_face:
