### ISSUE TITLE
Rules: Add legalese

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#508]
Jeremy Swanson @Jezzamonn 18:44
> Hey Mike! So I had to run LD past the lawyer folk at my work, and they had some suggestions for the ownership section to make it a bit more clear so they and similar companies can approve stuff easier. And also so LD doesn't get sued 
> 
> The suggestions were:
> 1. Label the section IP Ownership rather than just Ownership
> 2. Make it clear it applies to all LD events including compo & jam, as well as MiniLDs
> 3. Include the phrase "Ludum Dare will make no claim to ownership over copyright, patents or trademarks related to your game"
> 4. Something to say LD does ask for a license to embed the game on the website if people do that. Because apparently even embedding a thing is something you need a copyright for. But not ownership, just permission

**Comment by Jezzamonn** [comment]
Here's my suggested edit to the section already on the rules page:

### IP Ownership
Your game belongs to you. After all, you made it! Ludum Dare, its organizers and affiliates claim no ownership over any copyrights, patents or trademarks related to your game. This applies to all events run on the website, including both the Ludum Dare compo and the jam, as well as mini Ludum Dares, and any other event hosted by or on this site.

We do request the right to use your game for purpose of publicizing the event. If you do not wish your game to be publicized in this way, tell Mike. For the purpose of embedded games, we also request permissions to host your game on the website.

**Comment by mikekasprzak** [comment]
Moved ^
