### ISSUE TITLE
Persistence: Session abruptly ends 24/48 hours after login

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#576]
This is a spin off of #574 and #272.

Now that `redis` has been installed on the server to act solely as persistent session storage, the old persistence issues are no longer a problem. The 2nd PHP install on the server can no longer mess with the session expirations (plus the performance is far better).

However by design, the user has a cookie whose TTL does not change, and there's a check that after first look seems to expire the session after 24 hours. This is older code that I unfortunately never saw working until today when I changed how the server handled PHP sessions. So exactly what my logic here was, I just don't remember (was I trying to say regenerate everything after 24 hours?).

What does appear to be working: When you do something, the session's expiration/TTL gets reset (currently that's set to 48 hours by the server). Unfortunately that's just the session, and not the cookie. The cookie should probably not be constantly updated.

How it should probably work:
* A cookie should be good for ~24 hours, but its expiration/TTL should be set to a week or so.
* When a cookie is determined to be older than 24 hours, the server should overwrite it with a fresh cookie.

There could be an issue during those times when the client is performing asynchronous operations. There are certainly a few elements of page requests that could be classified as synchronous (fetching self or the root node), so if needed this can be done.

For reference, the file you want to work in should be this:

`/www/src/shrub/user/auth.php`

It's used by API calls to figure out whom is making the request.

**Comment by povrazor** [comment]
Also I was trying to avoid configuring redis on the VM, but it might be necessary to work all the bugs out of this. As is, the current configuration isn't relibale when it comes to session expiration.

**Comment by sgstair** [comment]
Yeah I seem to recall distinctly it does not work as how it should work described above :) I may take a closer look in the near future, now that I see what the intent was.

**Comment by povrazor** [comment]
In hindsight, this SHOULD be configured in the VM, that way we can test and fix persistence related bugs. I did this so long ago on the main server that I can't remember what it involved (possibly a small `php.ini` change). I'm going to flag this as a toolchain issues now too.
