### ISSUE TITLE
Write a "Timelapse Video" capturing guide

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#658]
I want more Timelapse videos!

* https://twitter.com/ludumdare/status/854330794504056833
* https://twitter.com/ludumdare/status/854018605083762688
* https://twitter.com/ludumdare/status/851751489236336642

I need a guide I can point people to for capturing timelapse videos. Something like this:

https://ldjam.com/events/ludum-dare/hosting-guide

* We have 3 OS's we care about (Windows, Linux, Mac).
* We should make recommendations
  * How frequent to take snapshots
  * How long to delay between frames
* How to assemble a video for YouTube
  * Specifically, tips for making standard MP4's would be useful for future features

Off hand, I would suggest that a Timelapse Video be not much longer than 6 minutes, but I would like to hear some discussion on this. Like I recently mentioned, I really like the format of my 30 second snippet videos I showcased on Twitter. It might even be possible to automate the generation of featured timelapse videos, but we need some agreed upon specs to do it.

PS: Chronolapse was made by an LD'er.

https://www.chronolapse.com/

**Comment by eLeit** [comment]
https://www.youtube.com/watch?v=f2ouAcfKHt4

Is a decent Chronolapse tutorial, although I could never get the encoding to work.
I actually recommend Blenders video editor for putting the movie together from the images. It was the best / easiest way of doing it I found. Other programs had problems with handling the large amount of images.

There's a great tutorial on video editing with blender here:
https://www.youtube.com/playlist?list=PLjyuVPBuorqIhlqZtoIvnAVQ3x18sNev4

**Comment by ChemiKhazi** [comment]
Windows only solutions:
- [ShareX](https://getsharex.com) also has auto capture options, as well as options to easily do video/gif captures.
- [VirtualDub](http://virtualdub.sourceforge.net/) can help put together the video in a GUI. Here's a [good tutorial](http://timelapseblog.com/2009/08/04/using-virtualdub-for-time-lapse/) for doing a timelapse video.

Cross platform:
- FFMPEG is a command line program that [can stitch together captured images](http://hamelot.io/visualization/using-ffmpeg-to-convert-a-set-of-images-into-a-video/) for the timelapse video.

**Comment by Aurel300** [comment]
How's this?

https://gist.github.com/Aurel300/9e8bf93ac9a8371990fcfdeccb9d051c

**Comment by zwrawr** [comment]
You canr't have a music section without https://incompetech.com/

**Comment by povrazor** [comment]
Awesome, that's a great start.

A couple things that jump out at me:

* Remove Vimeo. They've historically been against gaming videos, and I'd rather we just not deal with that. https://www.reddit.com/r/gamedev/comments/laua2/dont_use_vimeo_for_your_demo_videos/
* YouTube has a free music library too.
* the Demoscene has a lot of generally free music too, I'm just not sure where/what/who to recommend as a resource

**Comment by Aurel300** [comment]
Okay, edited. I put MOD archive for sorta kinda demoscene. I was considering Pouet, but those are generally finished productions, not very easy to use the music, and not sure about the licenses either.

**Comment by Jezzamonn** [comment]
Nice work Aurel! I'll leave my comments here too

I've made some timelapses and I've been editing some other videos. My opinion is:
If you want others to watch your timelapse, aim for around 5 minutes. But if you want to watch back yourself and see your own progress, it can be worth having more detail. You can always shorten a video by taking every second frame.

Also you also need to watch out for how much space all the screenshots will take on your hard-drive, that was the main constraint for me with a hidpi laptop.

**Comment by Jezzamonn** [comment]
Oh, also people should totally use the music from their own game in the timelapse!

**Comment by Aurel300** [comment]
My timelapses are generally in the 15-20 minute range, though I haven't investigated the viewer-retention stats :D You make some good points though, I will add them.

And yes, using music from your own game is ideal. If you have music :)

**Comment by Aurel300** [comment]
@Jezzamonn There, added your suggestions.

**Comment by TolMera** [comment]
Making a recommendation for anyone using Linux like me, use 'motion' it's a motion capture tool that you can use to capture pictures at regular intervals, while also only capturing images while there is any movement.  Very full featured.  If noone else has done this tomorrow, I might write this up for the Linux Users among us.

**Comment by Cerno-b** [comment]
What are best practices on the hard numbers: 
- What delay is best for timelapses? 
-- I usually create screenshots every 15s, but I feel the result appears to be very jaggy. 
- Frame rate?
-- 30 or 60fps?
- What is a good length of the final video?
-- I try to keep it around 5 minutes, but many videos are longer
-- This depends on the frame rate but also on how long you want to show each image.
- What are the best settings for uploading it to youtube (compression, etc).

My timelapses generally suck, so I wouldn't want to participate in writing such a guide, but I would be happy if people with better videos could offer their experience to fill in the above points.

**Comment by mikekasprzak** [comment]
Moved this discussion here: https://github.com/LudumDare/ludumdare.com/discussions/11
