### ISSUE TITLE
Write "Real World Gatherings" Guide

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#669]
I understand why (Global Game Jam), but I get requests for Ludum Dare's theme early way too often.

We have ratings. There are no prizes for the winners, but because things get rated, fairness is super important.

But also, fact is, we don't even have a theme until a few hours before the start of the event. Real live Democracy in action.

But given that anyone can enter anywhere, it's not really fair to give gatherings the theme early. The kid down the street who decided to work from home is penalized for his convenience.

Also, a key part of Ludum Dare is sharing progress. Sharing it via posts, via live streaming, tweets, etc. To have to muzzle a portion of the community because they have privileged information, that's uncool. 

Plus if it does get out early, that kind-of takes the wow out of the announcement. It's a moment many of us share. The pain and anguish of the theme you wanted to win not winning. We're together in this. :smile:

**Comment by OmarShehata** [comment]
I whole-heartedly commend the decision to hold onto the special moment when the theme is announced for everyone everywhere in the world at the same time! (Especially the part where we don't penalize people who can't work in a large/noisy environment and would rather work from home).
