### ISSUE TITLE
Drag+Drop image file on input-textarea runs code, and inserts some text

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#697]
Like you can do here on GitHub, add a way to drag+drop images in to the markup box.

When the input-textarea gets a dragdrop event, trigger a function. This will be some sort of image uploader. Remember the current position of the cursor, so that when the function finishes, it can insert some text that results in an embedded image.

GitHub inserts a placeholder. I'm not sure how important this is (it might be *shrug*).

**Comment by povrazor** [comment]
Uploading an image `doubletab.png`

Before:
![githubbefore](https://cloud.githubusercontent.com/assets/1570313/25258030/6cd54956-260a-11e7-9c51-0b1cdd1e5e25.png)

After:
![github-after](https://cloud.githubusercontent.com/assets/1570313/25258042/8389e4f4-260a-11e7-898d-7f80146089d8.png)
