### ISSUE TITLE
[Write Me] How to Submit My Game

### ISSUE THREAD

**Issue by zwrawr** [JammerCore/JammerCore#722]
This section at the bottom of the hosting guide needs filling in. 
![image](https://cloud.githubusercontent.com/assets/18352787/25293844/7493c24c-26d4-11e7-8765-8e631666aee7.png)

Should be based of this, or subsequent versions of this video
<blockquote class="twitter-video" data-lang="en"><p lang="en" dir="ltr">I&#39;m putting the final touches on this, but here is how you join the event (create a game) and make blog posts. <a href="https://twitter.com/hashtag/LDJAM?src=hash">#LDJAM</a> <a href="https://t.co/jWVgY7eqDk">pic.twitter.com/jWVgY7eqDk</a></p>&mdash; Mike Kasprzak🆚#LD38 (@mikekasprzak) <a href="https://twitter.com/mikekasprzak/status/855473182521872385">April 21, 2017</a></blockquote>

**Comment by povrazor** [comment]
I'm uploading a youtube version, but yeah.
