### ISSUE TITLE
Load new posts button

### ISSUE THREAD

**Issue by zwrawr** [JammerCore/JammerCore#725]
Kinda the opposite of the MORE button at the bottom

![image](https://cloud.githubusercontent.com/assets/18352787/25296614/1bfde1e6-26e1-11e7-9fe1-41a760dc6c75.png)

E.g. twitters implementation 
![image](https://cloud.githubusercontent.com/assets/18352787/25296631/2c4b8684-26e1-11e7-93a1-732646c2be60.png)

**Comment by povrazor** [comment]
Yes that needs to be done. The algorithm for fetching new posts is potentially buggy though. Most people wont notice it, but I need to fix it first. ;)

**Comment by mikekasprzak** [comment]
#549
