### ISSUE TITLE
Do something for sub-communities (IRC, Reddit, Twitch, Slack, Discord, Local, Hackerspaces, etc)

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#797]
Ludum Dare is big. So big, that our own community contains many smaller communities.

* Several IRC channels
* Reddit
* Twitch Community
* Many Slack groups
* Many Discords
* Local communities (schools, hacker spaces, meetup groups)
* Language specific communities

So really, need a community section to the website. A place you can go to to find other ways of communicating and making friends with folks.

**Comment by zwrawr** [comment]
I guess these can all be groups right? Then we need good discovery and suggestions.

**Comment by povrazor** [comment]
I don't imagine we'll have more than 100 of these initially, but I could be wrong. I want browsing communities to work exactly like how browsing games works (in fact, they may as well be items). Each community has cover art, and a page with details.

**Comment by lucasdealmeidasm** [comment]
We'd like to know if a link to the IRC channel will return to be featured on the front page

**Comment by local-minimum** [comment]
I'd say we need quick filter, tagging etc and possibly some that should be promoted to stay on top based on popularity or something?
