### ISSUE TITLE
Bootstrapping LD38 game thumbnails

### ISSUE THREAD

**Issue by mkalam-alami** [JammerCore/JammerCore#819]
I'm not sure if it's planned, but it might be useful to script something to set LD38 game thumbnails with the first picture from the blogpost.

Given that I already had to figure this out for Feedback Friends, maybe you'd be interested in the data: [ld38-thumbnails.zip](https://github.com/ludumdare/ludumdare/files/966451/ld38-thumbnails.zip) (just a CSV with a node ID + suggested picture path)

I can also give a try at contributing this, could we just set the picture directly in the "thumbnail" meta or would we need to set a different, maybe resized/cropped asset?

**Comment by povrazor** [comment]
I haven't done this yet. ;)

**Comment by mkalam-alami** [comment]
My bad! I only saw this as a patch following the implementation of covers. But yeah making it a feature in general might be useful.

**Comment by povrazor** [comment]
The real solution is when I'm forcing people to upload screenshots for the carousel, to fall-back on screenshot 1. Alas I haven't finished (or started) the carousel yet, but this is an option to fill in the data. The only downside is that I need to check if a user has a cover set before setting this.
