### ISSUE TITLE
Calendar Month Not Correct

### ISSUE THREAD

**Issue by ghost** [JammerCore/JammerCore#847]
When you hover over the judging date on the calendar, it says June 17, 2017 instead of May 17, 2017.
I live in the Midwest United States if that makes a difference (CDT).
![2ae28b257cb1ffe470eb4592e4c33a2a](https://cloud.githubusercontent.com/assets/5943561/25647294/65df5a8a-2f86-11e7-9c6f-e98a12d74ab9.png)

**Comment by zwrawr** [comment]
![image](https://cloud.githubusercontent.com/assets/18352787/25698033/30ee2fc4-30b5-11e7-8a88-4b39a7c2360d.png)

Happens for me too.  

I'm guessing it to do with the calendar not displaying multiple moths correctly.  
![image](https://cloud.githubusercontent.com/assets/18352787/25698087/63de1002-30b5-11e7-9ab9-e41fdf89c082.png)
![image](https://cloud.githubusercontent.com/assets/18352787/25698105/731b9292-30b5-11e7-8210-10f86a588516.png)

Seems to set the first cell to the current month, then increments the month.

**Comment by povrazor** [comment]
This could be related to the end-of-the-year bug I experienced. I had to introduce a hack to temporarily change the highlighted day to the following month. But than stopped working once April 30th got pushed off the display.

I'm guessing what's happening is when the current day of the week is in the beginning of a month that isn't all 7 days, we forgot to subtract 1 from the month.
