### ISSUE TITLE
Inline Asset: SketchFab

### ISSUE THREAD

**Issue by mikekasprzak** [JammerCore/JammerCore#89]
Consider adding Sketchfab support.

https://sketchfab.com/models/034a1a146e304161b7c45b9354ed2dfd

Was contactad by this dude.

https://twitter.com/RAWRsoft

**Comment by JanWerder** [comment]
So, when someone adds a link like "https://sketchfab.com/models/034a1a146e304161b7c45b9354ed2dfd" the site should turn it into the embeded viewer?

**Comment by povrazor** [comment]
Yes. The new standard way to embed everything is be to paste a URL to it on a standalone line. If we know what it is (YouTube, etc), we can convert it in to an embed. The key is to make sure that the website being embedded isn't CPU greedy, and wrap it if it is (i.e. a box, thumbnail in the background, big play button).
