### ISSUE TITLE
Post Jam Links

### ISSUE THREAD

**Issue by ajayyy** [JammerCore/JammerCore#964]
As seen here: https://ldjam.com/events/ludum-dare/38/planet-or-die/post-jam-releases-should-be-boldly-marked-as-such

> There are probably a number of games where people are tricked into playing and rating the post jam version* of the game. EG: Roboland**, where even a streamer got confused and played the post jam version. So I propose either post jam releases must be boldly declared as that, or the jam version must be boldly declared as that.
> 
> * : some changes after the jam is allowed, porting, and last second bug fixes (if you are doing more then 1 bug fix you are probably doing it wrong. (Source: You can’t add new features, but if something broke or didn’t work correctly as you were finishing up, you can fix this after the deadline. You are asked to highlight the changes you make)) **: Since this game was likely rated mostly by its post jam version I think the disqualification or reducing the rating received should happen. And yes the difference between the versions is huge enough to propose this.
> 
> PS: I don’t think the dev of roboland intentionally tried to deceive users.

Also, https://ldjam.com/events/ludum-dare/38/tribal-tension-twitch has issues. Since it is hosted on twitch, there is **only** a post jam version, and people are still rating. This is a problem.

**Comment by povrazor** [comment]
There's a `release` game type which is currently unused. My intention for that type is for the fancy post-LD commercial releases that folks spend several months or years on, but Post-LD games need a place too.

**Comment by local-minimum** [comment]
Well first thing is to nicely comment on a the game and indicate it is confusing and that they perhaps should make it clear which game should be rated.

Second thing, do we have a nicely written guide about what is OK and what is not? Otherwise perhaps another `write me` issue to produce that text?

**Comment by povrazor** [comment]
A write-me, pending some additional "add content" features.

**Comment by Jezzamonn** [comment]
Now that we have links we should probably revisit this!

**Comment by Jezzamonn** [comment]
An idea that I like that would allow for this is to have custom text for link types. As well as having the basic tags, it does give people extra flexibility. Kinda like itch's tagging system, you can make up new ones if you want but highly recommended to use existing ones.

**Comment by povrazor** [comment]
Yeah, you basically had this feature until I broke it. :wink:

The way tag filtering is going to work is that a list of node ids are passed to the query. Searching by node id is super quick, but obviously that means we need to be on-the-ball with adding them.

I had a little more time, I was hoping to make a hybrid drop-down box. One that can contain custom text, and one that can reference an index. The custom text option unfortunately wouldn't be filterable, but could become part of the search blobs.
