### ISSUE TITLE
Enhanced star rating display

### ISSUE THREAD

**Issue by quantumrain** [JammerCore/JammerCore#991]
I think it would be interesting to see the variance in a games rating in addition to the average value that's currently shown.

For example, here's a screenshot which shows how amazon displays star ratings for product reviews.

![image](https://cloud.githubusercontent.com/assets/713039/26279811/751e2b10-3db5-11e7-9f10-c3c164f10598.png)

This is interesting because it allows you to see if people were generally in agreement in their reviews, or if people had vastly different opinions/experiences.

I think this would also work well for visualising the ratings on Ludum Dare games, giving people some extra data points on how their rating might be shifting between jams.

It could also be used to throw a bone to people who haven't had enough ratings to get a standard ranking, they could be informed that they had less than the required 20 ratings for a position, but here's how the handful of people who did mark your game scored it.

But we would want a minimum bar on the number of ratings required for it to be shown, as if you have very few ratings on a game you could potentially link ratings given to comments, but above 5 or 6 ratings I think uncertainty is high enough that any individual rating would be harder to link.

I would suggest placing this visualisation at the bottom of the page, below the metrics, and breaking it down with a graph for each scoring category.

**Comment by pfefferminzz** [comment]
That would be a lot of graphs consuming pretty much space, but very insightful. I'd like to have this.

**Comment by Cerno-b** [comment]
I'm all for it. 

I would suggest showing this next to the ratings themselves, so that when you click a rating you switch the chart to the one you just clicked. Default would be Overall.

**Comment by povrazor** [comment]
We used to provide this data, but found it made some people a bit more angry about their results than they should have been (i.e. 1 star ratings). I'm not opposed to reintroducing it, but I do worry with our much larger community the "problem" will be amplified.

**Comment by Cerno-b** [comment]
Hm, I see your point. It seems people get angry at all kinds of stuff though, so maybe you could give it another spin for one of the next LDs and then poll whether people want to keep it? Although the poll result would be kind of obvious...

**Comment by pfefferminzz** [comment]
I think it's a huge difference to know if a 3 star rating is made of 2, 3, and 4 star ratings (consensus) or 1 and 5 star ratings (dissent). I'd really like to know this. Not to be angry about the 1 star ratings. It's valueable feeedback.

**Comment by local-minimum** [comment]
Personally I agree that it would be great feedback. I'm just concerned about voter anonymity. You really need quite a few votes for peoples votes to not be semi-identifiable with the comment texts and that might be problematic.

Maybe you only get to know this about your game and not every game.

Maybe you only get to know this if you specifically request a break down of the votes to shield those who don't want to know.

**Comment by pfefferminzz** [comment]
Oh, i never wanted to see it for every game, i'm specifically interested in the votes given for my game. Regarding voter anonymity, it could be shown only if a game is already ranked (or even X votes above) and if the the voting is over.

Hiding the statistics to those who do not want to know them behind a request or advanced statistics button sounds good, too.

**Comment by local-minimum** [comment]
Problem for me is the evaluation of identifiable/voter anonymity. One measure could be that no star category have more than 0 but less than 5 votes for the maker to get to see the stats. In that case I wonder if even my game with its 56 votes per category would be allowed, and I'm not that far down the `grade` list. Perhaps 5 is asking a lot, but if we care for voters feeling anonymous it probably shouldn't be much less either.

On the flip side, it could be an incentive to keep voting if this is a feature for the top tier voters...

**Comment by pfefferminzz** [comment]
I don't think that voters could be identified that easily, because only half of the voters leave a comment, i guess. And if you have 1 star ratings in each category, it does not mean that one user voted 1 star in all categories, because all votes are merged, of course. Asking vor 5 ratings in every star category is way too much. I would be fine with ~30 ratings per category, even that was hard to reach this LD 38 (where less than half of all entries reached 20).

**Comment by sgstair** [comment]
I have a design idea for this concept - I would add a tiny vertical bar graph next to the rating category with the data, which if you click it would pop out a larger window with the data in a more readable format. (think excel sparklines, if you have seen those)

**Comment by local-minimum** [comment]
I'm still a bit worried about this in terms of the internet safety of our users and their willingness to give frank criticism of a game. At least I don't think this should be done before we have comment anonymity in place. Even if a user can't be identified as the angry voter in a true sense, it can still be enough make the potential false connection between a particular low vote and a comment. The internet is a much more hostile place for some than others, and we really must be sensitive to that so that our events feel inclusive and safe.

**Comment by sgstair** [comment]
I don't really get that. This is very expressly a place for adults to come and sharpen their skills expressly by dealing with the chaos of unfiltered creation. Making a game in 48 hours and getting anything resembling raw criticism on it is way more hostile than anything else on the internet :)

You've seen the results page comment thread, some of these people are already inferring the presence of the angry voter that may or may not exist. People need to grow up.

**Comment by povrazor** [comment]
We have many adults, but we have many kids too (i.e. under 18, some even under 10).

It's true that many folks can "handle the truth", but care should be taken if we decide to bring this back.

**Comment by sgstair** [comment]
That actually is a good point. Someone on the ratings thread said there may have been a checkbox to "opt in" to allowing anonymous comments on the game, that is a pretty decent compromise, I think.

**Comment by povrazor** [comment]
I like that. Opt in to anonymous comments.
